# Full Corpus Build – AIC 2026 ASR Retrieval

This notebook builds the real ASR retrieval corpus from the competition videos.

The workflow is intentionally direct: the notebook imports `production/scripts/full_corpus.py` and calls its Python functions in the current process. Long-running work stays visible in the cell, and Phase 1 transcript checkpoints remain on Drive if Colab disconnects or the run is interrupted.

The notebook does not touch `production_smoke/` and does not activate a new release automatically.

## 1. Setup

Mount Drive, define the project paths, and check the source locations before any corpus work starts.

In [1]:
from google.colab import drive
drive.mount("/content/drive")

from pathlib import Path
import importlib.metadata as importlib_metadata
import json
import shutil
import sys

PROJECT_ROOT     = Path("/content/drive/MyDrive/aic26/asr_model_comparison")
VIDEO_ROOT       = Path("/content/drive/MyDrive/aic25/AIC_Video")
FPS_MAP_PATH     = Path("/content/drive/MyDrive/aic26/fps_map.json")
FULL_CORPUS_ROOT = PROJECT_ROOT / "production_full_corpus"
PRODUCTION_ROOT  = PROJECT_ROOT / "production"
SCRIPTS_ROOT     = PRODUCTION_ROOT / "scripts"
SCRIPT_PATH      = SCRIPTS_ROOT / "full_corpus.py"
RELEASES_ROOT    = FULL_CORPUS_ROOT / "phase2" / "releases"
REPORTS_ROOT     = FULL_CORPUS_ROOT / "reports"

required_paths = [PROJECT_ROOT, VIDEO_ROOT, FPS_MAP_PATH, PRODUCTION_ROOT / "asr_retrieval", SCRIPT_PATH]
for path in required_paths :
    if (not path.exists()) :
        raise FileNotFoundError(path)

video_resolved    = VIDEO_ROOT.resolve()
artifact_resolved = FULL_CORPUS_ROOT.resolve(strict = False)
if (video_resolved == artifact_resolved or video_resolved in artifact_resolved.parents) :
    raise RuntimeError("FULL_CORPUS_ROOT must not equal or sit inside VIDEO_ROOT")

with FPS_MAP_PATH.open("r", encoding = "utf-8") as file :
    fps_map = json.load(file)

mp4_count = sum(1 for path in VIDEO_ROOT.rglob("*.mp4") if path.is_file())
free_gib  = shutil.disk_usage(PROJECT_ROOT).free / 1024**3

print("PROJECT_ROOT     :", PROJECT_ROOT)
print("VIDEO_ROOT       :", VIDEO_ROOT)
print("FULL_CORPUS_ROOT :", FULL_CORPUS_ROOT)
print("MP4 files        :", f"{mp4_count:,}")
print("fps_map entries  :", f"{len(fps_map):,}")
print("Drive free       :", f"{free_gib:,.2f} GiB")

if (mp4_count != len(fps_map)) :
    print("Count mismatch detected. The inventory step below will show the exact missing and extra IDs.")

Mounted at /content/drive
PROJECT_ROOT     : /content/drive/MyDrive/aic26/asr_model_comparison
VIDEO_ROOT       : /content/drive/MyDrive/aic25/AIC_Video
FULL_CORPUS_ROOT : /content/drive/MyDrive/aic26/asr_model_comparison/production_full_corpus
MP4 files        : 1,478
fps_map entries  : 1,478
Drive free       : 2.33 GiB

### Phase 1 environment

Install the verified offline ASR stack in a fresh Phase 1 runtime. `%pip` runs directly in Colab; there is no Python subprocess wrapper around the notebook workflow.

In [2]:
%pip install Cython packaging "numba-cuda>=0.30.4" "nemo_toolkit[asr]==2.7.3" huggingface_hub soundfile scipy tqdm pandas

Requirement already satisfied: Cython in /usr/local/lib/python3.12/dist-packages (3.0.12)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (26.3)
Collecting numba-cuda>=0.30.4
  Downloading numba_cuda-0.30.4-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Collecting nemo_toolkit==2.7.3 (from nemo_toolkit[asr]==2.7.3)
  Downloading nemo_toolkit-2.7.3-py3-none-any.whl.metadata (77 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.4/77.4 kB 5.0 MB/s eta 0:00:00
Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.12/dist-packages (1.27.0)
Requirement already satisfied: soundfile in /usr/local/lib/python3.12/dist-packages (0.14.0)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (1.16.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (4.67.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.3)
Requirement already satisfied: cuda-bindings in /usr/local/lib/python3.12/dist-packages (from nemo_toolkit==2.7.3->nemo_toolkit[asr]==2.7.3) (12.9.7)
Collecting fsspec==2024.12.0 (from nemo_toolkit==2.7.3->nemo_toolkit[asr]==2.7.3)
  Downloading fsspec-2024.12.0-py3-none-any.whl.metadata (11 kB)
Collecting numexpr<2.14.0 (from nemo_toolkit==2.7.3->nemo_toolkit[asr]==2.7.3)
  Downloading numexpr-2.13.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (9.0 kB)
Requirement already satisfied: numpy>=1.22 in /usr/local/lib/python3.12/dist-packages (from nemo_toolkit==2.7.3->nemo_toolkit[asr]==2.7.3) (2.0.2)
Collecting onnx>=1.7.0 (from nemo_toolkit==2.7.3->nemo_toolkit[asr]==2.7.3)
  Downloading onnx-1.22.0-cp312-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (8.5 kB)
Requirement already satisfied: protobuf~=5.29.5 in /usr/local/lib/python3.12/dist-packages (from nemo_toolkit==2.7.3->nemo_toolkit[asr]==2.7.3) (5.29.6)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from nemo_toolkit==2.7.3->nemo_toolkit[asr]==2.7.3) (2.9.0.post0)
Collecting ruamel.yaml (from nemo_toolkit==2.7.3->nemo_toolkit[asr]==2.7.3)
  Downloading ruamel_yaml-0.19.1-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from nemo_toolkit==2.7.3->nemo_toolkit[asr]==2.7.3) (1.6.1)
Requirement already satisfied: setuptools>=70.0.0 in /usr/local/lib/python3.12/dist-packages (from nemo_toolkit==2.7.3->nemo_toolkit[asr]==2.7.3) (75.2.0)
Requirement already satisfied: tensorboard in /usr/local/lib/python3.12/dist-packages (from nemo_toolkit==2.7.3->nemo_toolkit[asr]==2.7.3) (2.20.0)
Requirement already satisfied: text-unidecode in /usr/local/lib/python3.12/dist-packages (from nemo_toolkit==2.7.3->nemo_toolkit[asr]==2.7.3) (1.3)
Requirement already satisfied: torch>=2.6.0 in /usr/local/lib/python3.12/dist-packages (from nemo_toolkit==2.7.3->nemo_toolkit[asr]==2.7.3) (2.11.0+cu128)
Collecting wget (from nemo_toolkit==2.7.3->nemo_toolkit[asr]==2.7.3)
  Downloading wget-3.2.zip (10 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from nemo_toolkit==2.7.3->nemo_toolkit[asr]==2.7.3) (2.3.0)
Collecting braceexpand (from nemo_toolkit[asr]==2.7.3)
  Downloading braceexpand-0.1.7-py2.py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: editdistance in /usr/local/lib/python3.12/dist-packages (from nemo_toolkit[asr]==2.7.3) (0.8.1)
Requirement already satisfied: einops in /usr/local/lib/python3.12/dist-packages (from nemo_toolkit[asr]==2.7.3) (0.8.2)
Collecting jiwer<4.0.0,>=3.1.0 (from nemo_toolkit[asr]==2.7.3)
  Downloading jiwer-3.1.0-py3-none-any.whl.metadata (2.6 kB)
Collecting kaldi-python-io (from nemo_toolkit[asr]==2.7.3)
  Downloading kaldi-python-io-1.2.2.tar.gz (8.8 kB)
  Preparing metadata (setup.py) ... done
Collecting kaldialign<=0.9.1 (from nemo_toolkit[asr]==2.7.3)
  Downloading kaldialign-0.9.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.3 kB)
Collecting lhotse>=1.32.2 (from nemo_toolkit[asr]==2.7.3)
  Downloading lhotse-1.33.0-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: librosa>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from nemo_toolkit[asr]==2.7.3) (0.11.0)
Collecting marshmallow (from nemo_toolkit[asr]==2.7.3)
  Downloading marshmallow-4.3.1-py3-none-any.whl.metadata (6.8 kB)
Collecting optuna (from nemo_toolkit[asr]==2.7.3)
  Downloading optuna-4.9.0-py3-none-any.whl.metadata (15 kB)
Collecting pyannote.core (from nemo_toolkit[asr]==2.7.3)
  Downloading pyannote_core-6.0.1-py3-none-any.whl.metadata (1.9 kB)
Collecting pyannote.metrics (from nemo_toolkit[asr]==2.7.3)
  Downloading pyannote_metrics-4.1-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: pydub in /usr/local/lib/python3.12/dist-packages (from nemo_toolkit[asr]==2.7.3) (0.25.1)
Collecting pyloudnorm (from nemo_toolkit[asr]==2.7.3)
  Downloading pyloudnorm-0.2.0-py3-none-any.whl.metadata (6.6 kB)
Collecting resampy (from nemo_toolkit[asr]==2.7.3)
  Downloading resampy-0.4.3-py3-none-any.whl.metadata (3.0 kB)
Collecting sacrebleu (from nemo_toolkit[asr]==2.7.3)
  Downloading sacrebleu-2.6.0-py3-none-any.whl.metadata (39 kB)
Collecting sox<=1.5.0 (from nemo_toolkit[asr]==2.7.3)
  Downloading sox-1.5.0.tar.gz (63 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.9/63.9 kB 8.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting whisper_normalizer (from nemo_toolkit[asr]==2.7.3)
  Downloading whisper_normalizer-0.1.15-py3-none-any.whl.metadata (8.3 kB)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (from nemo_toolkit[asr]==2.7.3) (4.0.0)
Requirement already satisfied: inflect in /usr/local/lib/python3.12/dist-packages (from nemo_toolkit[asr]==2.7.3) (7.5.0)
Collecting mediapy==1.1.6 (from nemo_toolkit[asr]==2.7.3)
  Downloading mediapy-1.1.6-py3-none-any.whl.metadata (4.8 kB)
Collecting sacremoses>=0.0.43 (from nemo_toolkit[asr]==2.7.3)
  Downloading sacremoses-0.2.0-py3-none-any.whl.metadata (8.8 kB)
Requirement already satisfied: sentencepiece<1.0.0 in /usr/local/lib/python3.12/dist-packages (from nemo_toolkit[asr]==2.7.3) (0.2.2)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.12/dist-packages (from nemo_toolkit[asr]==2.7.3) (3.1.2)
Collecting fiddle (from nemo_toolkit[asr]==2.7.3)
  Downloading fiddle-0.3.0-py3-none-any.whl.metadata (2.3 kB)
Collecting hydra-core<=1.3.2,>1.3 (from nemo_toolkit[asr]==2.7.3)
  Downloading hydra_core-1.3.2-py3-none-any.whl.metadata (5.5 kB)
Collecting lightning<=2.4.0,>2.2.1 (from nemo_toolkit[asr]==2.7.3)
  Downloading lightning-2.4.0-py3-none-any.whl.metadata (38 kB)
Collecting omegaconf<=2.3 (from nemo_toolkit[asr]==2.7.3)
  Downloading omegaconf-2.3.0-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: peft in /usr/local/lib/python3.12/dist-packages (from nemo_toolkit[asr]==2.7.3) (0.20.0)
Collecting torchmetrics>=0.11.0 (from nemo_toolkit[asr]==2.7.3)
  Downloading torchmetrics-1.9.0-py3-none-any.whl.metadata (23 kB)
Collecting transformers~=4.57.0 (from nemo_toolkit[asr]==2.7.3)
  Downloading transformers-4.57.6-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 3.6 MB/s eta 0:00:00
Requirement already satisfied: wandb in /usr/local/lib/python3.12/dist-packages (from nemo_toolkit[asr]==2.7.3) (0.28.2)
Collecting webdataset>=0.2.86 (from nemo_toolkit[asr]==2.7.3)
  Downloading webdataset-1.0.2-py3-none-any.whl.metadata (12 kB)
Collecting nv_one_logger_core>=2.3.1 (from nemo_toolkit[asr]==2.7.3)
  Downloading nv_one_logger_core-2.3.1-py3-none-any.whl.metadata (12 kB)
Collecting nv_one_logger_training_telemetry>=2.3.1 (from nemo_toolkit[asr]==2.7.3)
  Downloading nv_one_logger_training_telemetry-2.3.1-py3-none-any.whl.metadata (27 kB)
Collecting nv_one_logger_pytorch_lightning_integration>=2.3.1 (from nemo_toolkit[asr]==2.7.3)
  Downloading nv_one_logger_pytorch_lightning_integration-2.3.1-py3-none-any.whl.metadata (8.9 kB)
Requirement already satisfied: ipython in /usr/local/lib/python3.12/dist-packages (from mediapy==1.1.6->nemo_toolkit[asr]==2.7.3) (7.34.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from mediapy==1.1.6->nemo_toolkit[asr]==2.7.3) (3.10.0)
Requirement already satisfied: Pillow in /usr/local/lib/python3.12/dist-packages (from mediapy==1.1.6->nemo_toolkit[asr]==2.7.3) (11.3.0)
Requirement already satisfied: numba>=0.60.0 in /usr/local/lib/python3.12/dist-packages (from numba-cuda>=0.30.4) (0.60.0)
Collecting cuda-core<2.0.0,>=0.5.1 (from numba-cuda>=0.30.4)
  Downloading cuda_core-1.1.1-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (3.3 kB)
Requirement already satisfied: cuda-pathfinder<2.0.0,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from numba-cuda>=0.30.4) (1.6.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (3.32.3)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (1.6.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (0.28.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (6.0.3)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.16.0)
Requirement already satisfied: cffi>=1.0 in /usr/local/lib/python3.12/dist-packages (from soundfile) (2.1.1)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.0->soundfile) (3.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub) (0.16.0)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in /usr/local/lib/python3.12/dist-packages (from hydra-core<=1.3.2,>1.3->nemo_toolkit[asr]==2.7.3) (4.9.3)
Collecting rapidfuzz>=3.9.7 (from jiwer<4.0.0,>=3.1.0->nemo_toolkit[asr]==2.7.3)
  Downloading rapidfuzz-3.14.5-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (12 kB)
Requirement already satisfied: audioread>=2.1.9 in /usr/local/lib/python3.12/dist-packages (from lhotse>=1.32.2->nemo_toolkit[asr]==2.7.3) (3.1.0)
Collecting cytoolz>=0.10.1 (from lhotse>=1.32.2->nemo_toolkit[asr]==2.7.3)
  Downloading cytoolz-1.1.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (5.2 kB)
Collecting intervaltree>=3.1.0 (from lhotse>=1.32.2->nemo_toolkit[asr]==2.7.3)
  Downloading intervaltree-3.2.1-py2.py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: tabulate>=0.8.1 in /usr/local/lib/python3.12/dist-packages (from lhotse>=1.32.2->nemo_toolkit[asr]==2.7.3) (0.9.0)
Requirement already satisfied: joblib>=1.0 in /usr/local/lib/python3.12/dist-packages (from librosa>=0.10.1->nemo_toolkit[asr]==2.7.3) (1.5.3)
Requirement already satisfied: decorator>=4.3.0 in /usr/local/lib/python3.12/dist-packages (from librosa>=0.10.1->nemo_toolkit[asr]==2.7.3) (4.4.2)
Requirement already satisfied: pooch>=1.1 in /usr/local/lib/python3.12/dist-packages (from librosa>=0.10.1->nemo_toolkit[asr]==2.7.3) (1.9.0)
Requirement already satisfied: soxr>=0.3.2 in /usr/local/lib/python3.12/dist-packages (from librosa>=0.10.1->nemo_toolkit[asr]==2.7.3) (1.1.0)
Requirement already satisfied: lazy_loader>=0.1 in /usr/local/lib/python3.12/dist-packages (from librosa>=0.10.1->nemo_toolkit[asr]==2.7.3) (0.5)
Requirement already satisfied: msgpack>=1.0 in /usr/local/lib/python3.12/dist-packages (from librosa>=0.10.1->nemo_toolkit[asr]==2.7.3) (1.2.1)
Collecting lightning-utilities<2.0,>=0.10.0 (from lightning<=2.4.0,>2.2.1->nemo_toolkit[asr]==2.7.3)
  Downloading lightning_utilities-0.15.3-py3-none-any.whl.metadata (5.5 kB)
Collecting packaging
  Downloading packaging-24.2-py3-none-any.whl.metadata (3.2 kB)
Collecting pytorch-lightning (from lightning<=2.4.0,>2.2.1->nemo_toolkit[asr]==2.7.3)
  Downloading pytorch_lightning-2.6.5-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba>=0.60.0->numba-cuda>=0.30.4) (0.43.0)
Collecting StrEnum<0.5.0,>=0.4.0 (from nv_one_logger_core>=2.3.1->nemo_toolkit[asr]==2.7.3)
  Downloading StrEnum-0.4.15-py3-none-any.whl.metadata (5.3 kB)
Collecting overrides<8.0.0,>=7.7.0 (from nv_one_logger_core>=2.3.1->nemo_toolkit[asr]==2.7.3)
  Downloading overrides-7.7.0-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: pydantic<3.0.0,>=2.10.6 in /usr/local/lib/python3.12/dist-packages (from nv_one_logger_core>=2.3.1->nemo_toolkit[asr]==2.7.3) (2.13.4)
Requirement already satisfied: toml<0.11.0,>=0.10.2 in /usr/local/lib/python3.12/dist-packages (from nv_one_logger_core>=2.3.1->nemo_toolkit[asr]==2.7.3) (0.10.2)
Collecting setuptools>=70.0.0 (from nemo_toolkit==2.7.3->nemo_toolkit[asr]==2.7.3)
  Downloading setuptools-84.0.0-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: ml_dtypes>=0.5.4 in /usr/local/lib/python3.12/dist-packages (from onnx>=1.7.0->nemo_toolkit==2.7.3->nemo_toolkit[asr]==2.7.3) (0.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->nemo_toolkit==2.7.3->nemo_toolkit[asr]==2.7.3) (1.17.0)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from sacremoses>=0.0.43->nemo_toolkit[asr]==2.7.3) (2025.11.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->nemo_toolkit==2.7.3->nemo_toolkit[asr]==2.7.3) (3.6.0)
  Downloading setuptools-81.0.0-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.6.0->nemo_toolkit==2.7.3->nemo_toolkit[asr]==2.7.3) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.6.0->nemo_toolkit==2.7.3->nemo_toolkit[asr]==2.7.3) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.6.0->nemo_toolkit==2.7.3->nemo_toolkit[asr]==2.7.3) (3.1.6)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.6.0->nemo_toolkit==2.7.3->nemo_toolkit[asr]==2.7.3) (12.8.1)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch>=2.6.0->nemo_toolkit==2.7.3->nemo_toolkit[asr]==2.7.3) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.6.0->nemo_toolkit==2.7.3->nemo_toolkit[asr]==2.7.3) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch>=2.6.0->nemo_toolkit==2.7.3->nemo_toolkit[asr]==2.7.3) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.6.0->nemo_toolkit==2.7.3->nemo_toolkit[asr]==2.7.3) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.6.0->nemo_toolkit==2.7.3->nemo_toolkit[asr]==2.7.3) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.6.0->nemo_toolkit==2.7.3->nemo_toolkit[asr]==2.7.3) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.6.0->nemo_toolkit==2.7.3->nemo_toolkit[asr]==2.7.3) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.6.0->nemo_toolkit==2.7.3->nemo_toolkit[asr]==2.7.3) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.6.0->nemo_toolkit==2.7.3->nemo_toolkit[asr]==2.7.3) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.6.0->nemo_toolkit==2.7.3->nemo_toolkit[asr]==2.7.3) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.6.0->nemo_toolkit==2.7.3->nemo_toolkit[asr]==2.7.3) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.6.0->nemo_toolkit==2.7.3->nemo_toolkit[asr]==2.7.3) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.6.0->nemo_toolkit==2.7.3->nemo_toolkit[asr]==2.7.3) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.6.0->nemo_toolkit==2.7.3->nemo_toolkit[asr]==2.7.3) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.6.0->nemo_toolkit==2.7.3->nemo_toolkit[asr]==2.7.3) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.6.0->nemo_toolkit==2.7.3->nemo_toolkit[asr]==2.7.3) (12.8.90)
Collecting huggingface_hub

In [3]:
import shutil
import sys

import nemo

from nemo.utils import logging as nemo_logging
nemo_logging.set_verbosity(nemo_logging.ERROR)

import numba
import numba_cuda
import torch

version_parts = tuple(int(part) for part in torch.__version__.split("+")[0].split(".")[ : 2])

if (version_parts < (2, 7)) :
    raise RuntimeError(f"Production Parakeet requires PyTorch >= 2.7; found {torch.__version__}")

if (not torch.cuda.is_available()) :
    raise RuntimeError("CUDA is not available. Select a GPU runtime before Phase 1.")

for executable in ["ffmpeg", "ffprobe"] :
    if (shutil.which(executable) is None) :
        raise RuntimeError(f"Required executable is missing: {executable}")

print("Python     :", sys.version.split()[0])
print("PyTorch    :", torch.__version__)
print("CUDA       :", torch.version.cuda)
print("GPU        :", torch.cuda.get_device_name(0))
print("NeMo       :", nemo.__version__)
print("Numba      :", numba.__version__)
print("Numba CUDA :", numba_cuda.__version__)
print("ffmpeg     :", shutil.which("ffmpeg"))
print("ffprobe    :", shutil.which("ffprobe"))

Python     : 3.12.13
PyTorch    : 2.11.0+cu128
CUDA       : 12.8
GPU        : Tesla T4
NeMo       : 2.7.3
Numba      : 0.60.0
Numba CUDA : 0.30.4
ffmpeg     : /usr/bin/ffmpeg
ffprobe    : /usr/bin/ffprobe

### Import the corpus helpers

The notebook calls these functions directly. This cell is also the only helper-import cell you need to rerun after the Phase 2 runtime restart.

In [4]:
import pandas as pd

if (str(SCRIPTS_ROOT) not in sys.path) :
    sys.path.insert(0, str(SCRIPTS_ROOT))

from full_corpus import (
    activate_corpus_release,
    audit_phase1,
    benchmark_release,
    build_corpus_release,
    load_inventory,
    make_corpus_build_config,
    make_offline_config,
    phase1_acceptance,
    prepare_inventory,
    read_json,
    scan_phase1,
    select_pilot_ids,
    transcribe_corpus,
    validate_corpus_release,
)
from asr_retrieval.config import parakeet_identity, window_policy_identity
from asr_retrieval.postprocess import POSTPROCESS_VERSION

offline_config = make_offline_config(FULL_CORPUS_ROOT)
corpus_config  = make_corpus_build_config(FULL_CORPUS_ROOT)

print("Parakeet model        :", offline_config.parakeet.model_name)
print("Parakeet revision     :", offline_config.parakeet.revision)
print("Parakeet identity     :", parakeet_identity(offline_config.parakeet))
print("Window seconds        :", offline_config.audio.window_seconds)
print("Stride seconds        :", offline_config.audio.stride_seconds)
print("Window policy identity:", window_policy_identity(offline_config.audio))
print("Postprocess version   :", POSTPROCESS_VERSION)
print("BM25 k1 / b           :", corpus_config.bm25.k1, "/", corpus_config.bm25.b)
print("E5 model              :", corpus_config.e5.model_name)
print("E5 revision           :", corpus_config.e5.revision)

Parakeet model        : nvidia/parakeet-ctc-0.6b-Vietnamese
Parakeet revision     : b0493142b49458810324e3db8be9e8e07b4ebc17
Parakeet identity     : {'model_name': 'nvidia/parakeet-ctc-0.6b-Vietnamese', 'model_filename': 'parakeet-ctc-0.6b-vi.nemo', 'revision': 'b0493142b49458810324e3db8be9e8e07b4ebc17', 'timestamps': True, 'decoder': 'greedy_ctc', 'dtype': 'float32', 'batch_size': 1}
Window seconds        : 60.0
Stride seconds        : 45.0
Window policy identity: 2e9bc23da7904c796817114f3cfc438b1d87dafcc08a286337581e66d7ffb679
Postprocess version   : 1.1
BM25 k1 / b           : 1.5 / 0.75
E5 model              : intfloat/multilingual-e5-large-instruct
E5 revision           : 274baa43b0e13e37fafa6428dbc7938e62e5c439

## 2. Inventory and pilot

The inventory is the authoritative list of source videos. The first run freezes it; later runs verify that the MP4 paths, sizes, modification times, and FPS values still match.

### Freeze or verify the inventory

In [ ]:
inventory_rows, inventory_summary = prepare_inventory(
    video_root    = VIDEO_ROOT,
    fps_map_path  = FPS_MAP_PATH,
    artifact_root = FULL_CORPUS_ROOT,
)

inventory_df = pd.DataFrame(inventory_rows)
inventory_df["prefix"] = inventory_df["video_id"].str.split("_").str[0]

print("Inventory identity:", inventory_summary["inventory_identity"])
print("Videos            :", f"{len(inventory_rows):,}")
print("Source size       :", f"{inventory_summary['total_size_bytes'] / 1024**3:,.2f} GiB")
display(inventory_df.head(10))
display(inventory_df.groupby("prefix").size().rename("videos").to_frame())
display((inventory_df["size_bytes"] / 1024**2).describe().rename("size_MiB").to_frame())

Inventory identity: 466408aa4d89e7e0412def939a5281081c17dfa1c151f8bf34e4538e7e1b23b4
Videos            : 1,478
Source size       : 228.31 GiB

,video_id,source_path,relative_source_path,size_bytes,mtime_ns,expected_from_fps_map,fps,prefix
0,K01_V001,/content/drive/MyDrive/aic25/AIC_Video/K01/K01...,K01/K01_V001.mp4,425366086,1757133956000000000,True,25.0,K01
1,K01_V002,/content/drive/MyDrive/aic25/AIC_Video/K01/K01...,K01/K01_V002.mp4,482719300,1757133962000000000,True,30.0,K01
2,K01_V003,/content/drive/MyDrive/aic25/AIC_Video/K01/K01...,K01/K01_V003.mp4,272767047,1757133969000000000,True,30.0,K01
3,K01_V004,/content/drive/MyDrive/aic25/AIC_Video/K01/K01...,K01/K01_V004.mp4,240594463,1757133976000000000,True,25.0,K01
4,K01_V005,/content/drive/MyDrive/aic25/AIC_Video/K01/K01...,K01/K01_V005.mp4,440495474,1757133981000000000,True,25.0,K01
5,K01_V006,/content/drive/MyDrive/aic25/AIC_Video/K01/K01...,K01/K01_V006.mp4,386351530,1757133989000000000,True,30.0,K01
6,K01_V007,/content/drive/MyDrive/aic25/AIC_Video/K01/K01...,K01/K01_V007.mp4,438690481,1757133997000000000,True,30.0,K01
7,K01_V008,/content/drive/MyDrive/aic25/AIC_Video/K01/K01...,K01/K01_V008.mp4,460110435,1757134006000000000,True,30.0,K01
8,K01_V009,/content/drive/MyDrive/aic25/AIC_Video/K01/K01...,K01/K01_V009.mp4,272572902,1757134015000000000,True,30.0,K01
9,K01_V010,/content/drive/MyDrive/aic25/AIC_Video/K01/K01...,K01/K01_V010.mp4,532551829,1757134020000000000,True,30.0,K01

        videos
prefix
K01         31
K02         31
K03         29
K04         30
K05         31
K06         31
K07         31
K08         30
K09         28
K10         28
K11         31
K12         31
K13         30
K14         30
K15         31
K16         32
K17         30
K18         28
K19         31
K20         31
L21         29
L22         31
L23         25
L24         43
L25         88
L26        498
L27         16
L28         24
L29         23
L30         96

          size_MiB
count  1478.000000
mean    158.180712
std     106.350069
min       9.037562
25%      66.123909
50%     135.144695
75%     233.188612
max     589.241631

### Pilot

The pilot selects eight deterministic videos spread across corpus prefixes. It writes into the real Phase 1 workspace, so successful pilot artifacts are reused by the full run.

In [ ]:
pilot_ids = select_pilot_ids(inventory_rows, count = 8)
print("Pilot IDs:", pilot_ids)

pilot_report = transcribe_corpus(
    artifact_root = FULL_CORPUS_ROOT,
    video_ids     = pilot_ids,
)

pilot_status_rows, _ = scan_phase1(FULL_CORPUS_ROOT)
pilot_status_df = pd.DataFrame(pilot_status_rows)
pilot_status_df = pilot_status_df[pilot_status_df["video_id"].isin(pilot_ids)].reset_index(drop = True)
display(pilot_status_df)

if (pilot_report["failures"]) :
    raise RuntimeError(f"Pilot source failures: {pilot_report['failures']}")
if (not pilot_status_df["complete"].all()) :
    raise RuntimeError("One or more pilot artifacts are incomplete")
if (pilot_status_df["eligible_windows"].sum() <= 0) :
    raise RuntimeError("The pilot produced no retrieval-eligible transcript windows")
print("Pilot: PASS")

Pilot IDs: ['K01_V016', 'K05_V016', 'K09_V015', 'K13_V016', 'K18_V015', 'L22_V016', 'L26_V250', 'L30_V049']
Corpus complete : 740 / 1,478
Selected        : 8
Skipped         : 8
To process      : 0
Nothing to transcribe. Parakeet was not loaded.

,video_id,artifact_path,artifact_exists,complete,window_count,ok_nonempty_windows,ok_empty_windows,failed_windows,eligible_windows,classification,invalid_reason
0,K01_V016,/content/drive/MyDrive/aic26/asr_model_compari...,True,True,24,24,0,0,24,complete_clean,None
1,K05_V016,/content/drive/MyDrive/aic26/asr_model_compari...,True,True,18,18,0,0,18,complete_clean,None
2,K09_V015,/content/drive/MyDrive/aic26/asr_model_compari...,True,True,26,26,0,0,26,complete_clean,None
3,K13_V016,/content/drive/MyDrive/aic26/asr_model_compari...,True,True,23,23,0,0,23,complete_clean,None
4,K18_V015,/content/drive/MyDrive/aic26/asr_model_compari...,True,True,24,24,0,0,24,complete_clean,None
5,L22_V016,/content/drive/MyDrive/aic26/asr_model_compari...,True,True,32,32,0,0,32,complete_clean,None
6,L26_V250,/content/drive/MyDrive/aic26/asr_model_compari...,True,True,7,7,0,0,7,complete_clean,None
7,L30_V049,/content/drive/MyDrive/aic26/asr_model_compari...,True,True,4,4,0,0,4,complete_clean,None

Pilot: PASS

In [ ]:
# Rerun the same pilot. Complete videos should be skipped before Parakeet is loaded.
resume_report = transcribe_corpus(
    artifact_root = FULL_CORPUS_ROOT,
    video_ids     = pilot_ids,
)

if (resume_report["work_video_count"] != 0) :
    raise RuntimeError("Pilot resume check failed: completed videos were reopened")
print("Pilot resume check: PASS")

for video_id in pilot_ids :
    transcript_path = FULL_CORPUS_ROOT / "phase1" / "transcripts" / f"{video_id}.json"
    payload         = read_json(transcript_path)
    eligible        = [window for window in payload["windows"] if window.get("eligible")]
    example         = eligible[0]["retrieval_text"] if eligible else "<no retrieval-eligible window>"
    print(f"\n{video_id} | windows={len(payload['windows'])} | eligible={len(eligible)}")
    print(example[ : 400])

Corpus complete : 740 / 1,478
Selected        : 8
Skipped         : 8
To process      : 0
Nothing to transcribe. Parakeet was not loaded.
Pilot resume check: PASS

K01_V016 | windows=24 | eligible=24
h kính chào quý vị đây là chương trình sáu mươi giây chiều của đài truyền hình thành phố hồ chí minh h hôm nay mười sáu tháng mười chương trình sẽ có những nội dung nổi bật sau đây những khu vực tại thành phố hồ chí minh có nguy cơ ngập do triều cường cuối tuần này nỗ lực nhiệt sâu đầu đen gây hại vườ dừa tại tỉnh tiền giang bầu cử mỹ nóng lên từ ngày cử tri một màn chiếm địa đi bỏ phiếu sớm sáng

K05_V016 | windows=18 | eligible=18
xin kính chào quý vị xin mời quý vị theo dõi chương trình sáu mươi giây sáng đầu tuần của đài truyền hình thành phố hồ chí minh chương trình sáng nay ngày mười sáu tháng mười hai năm hai ngàn không trăm hai mươi bốn sẽ có những nội dung chính sau đây đã đưa được hơn ba trăm năm mươi người bị mắc kẹt do sự cố sạt lở đèo khánh lê về nơi an toàn khá tham quan trải nghiệm mua sắm chợ giáng sinh độc đá

K09_V015 | windows=26 | eligible=26
k kính thưa quý vị chúng tôi rất vui được gặp lại quý vị trong chương trình sáu mươi giây sáng thứ b bảy mười lăm tháng hai hy vọng quý vị đang trải qua những thời khắc vui vẻải mái bên người th thân và ngay sau đây sáu mươi giây sâm m mang đến cho quý vị những thông tin đáng quan tâm trong ngày diễn ra trong nước và thế giới ngành nhôm tìm giải pháp ứng phó việt mỹ áp thuế hai mươi lăm phần trăm

K13_V016 | windows=23 | eligible=23
ch chào mừng quý vị đến với chương trình sáu mươi giây của đài truyền hình thành phố hồ chí minh chương trình sáng nay có những thông tin nổi bật sâu đề xuất áp dụng hai mức thu phí đối với các tuyến cao tốc do nhà nước đầu tư đàn voi rừng khoảng bảy con xuất hiện phá một số vườn rẫy của các hộ dân khởi tố vụ án vụ việc sản xuất buôn bán và tiêu thụ sữa bột giả quy mô lớn nỗ lực khống chế vụ cháy

K18_V015 | windows=24 | eligible=24
k kính chào quý vị chương trình sáu mươi giây chiều tối thứ hai ngày mười sáu tháng sáu năm hai ngàn không trăm hai mươi lăm sẽ gửi đến quý vị những hoạt động đáng quan tâm và chú ý diễn ra trong ngày ngay sau đây là những nội dung chính có trong chương trình hôm nay thông qua luật nh nhà giáo lương nh nhà giáo cao nhất không cấm về thêm mừa kéo dài hơn một tiếng nhiều tuyến đường ở đà lạt ngập sâ

L22_V016 | windows=32 | eligible=32
k kính chào quý vị chúng tôi rất vui được gặp lại quý vị trong chương trình sáu mươi giây chiều thứ sáu ngày mười sáu tháng tám hy vọng quý vị đang trải qua những thời khắc vui vẻ thoải mái bên người thân và ngay sau đây sáu mươi giây sẽ mang đến cho quý vị những thông tin được quan tâm trong ngày diễn ra trong nước và thế giới thành phố hồ chí minh hợp tác cùng tỉnh tây ninh khai thác các tu du l

L26_V250 | windows=7 | eligible=7
tr món ngon mỗi ngày chàoanh phương chào anhũ em làm gì mà mí m nghĩa ta ướt múc mỏi vậy ta tuyệt t tác nghệ thuậtè tiên r đổi giá nghệ thuật gì độc đáo chỗ là em tự ủ đó đang vũ vậy ta giá mà chúng ta tự làm thì an toàn hơn dạ đây đây tuyệt tác nghệ thuật của anh anh mới lột xong một cái dĩa tômaiệt t tác nghệ thuật này sẽ làm được món gì đây canh chua tôm các bạn hãy canh chua thường thường thì

L30_V049 | windows=4 | eligible=4
chứ vào sáng thứ b ba và thứ năm hàng tuần những phụ huynh có hoàn cảnh khó khăn trên địa bàn thành phố thủ đức thành phố hồ chí minh lại dẫn con đến lớp học bơi miễn phí tại đây các em được trang bị áo phao kín bơi để sẵn sàng cho giờ học bổ ích với phương châm thêm nhiều trẻ em biết bơi sẽ không còn trẻ bị đuối nước trung tâmể dục thể thao thành phố thủ đức mở các lớp phổ cập bơi hoàn toàn miễn

## 3. Phase 1 transcription

This is the long-running ASR step. It runs directly in the notebook process with visible `tqdm` progress.

Completed videos are skipped. Partial videos are handed back to the existing production `transcribe_video()` logic, which validates the source and resumes from its saved window checkpoints. The cell can be interrupted or lost and rerun later.

In [ ]:
# Long-running cell. Safe to rerun after a Colab disconnect or manual interruption.
transcription_report = transcribe_corpus(
    artifact_root = FULL_CORPUS_ROOT,
)

Corpus complete : 1,170 / 1,478
Selected        : 1,478
Skipped         : 1,170
To process      : 308
Loading Parakeet...
Loaded: nvidia/parakeet-ctc-0.6b-Vietnamese @ b0493142b49458810324e3db8be9e8e07b4ebc17
[1,171/1,478] K19_V003 | FAILED | RuntimeError: Video is already owned by another transcription worker: K19_V003
[1,172/1,478] L25_V007 | FAILED | RuntimeError: Video is already owned by another transcription worker: L25_V007
[1,173/1,478] L26_V351 | DONE | windows=7 | eligible=7 | 7.6s
[1,174/1,478] L26_V352 | DONE | windows=7 | eligible=7 | 10.6s
[1,175/1,478] L26_V353 | DONE | windows=7 | eligible=7 | 11.1s
[1,176/1,478] L26_V354 | DONE | windows=7 | eligible=7 | 11.3s
[1,177/1,478] L26_V355 | DONE | windows=7 | eligible=7 | 9.7s
[1,178/1,478] L26_V356 | DONE | windows=7 | eligible=7 | 10.6s
[1,179/1,478] L26_V357 | DONE | windows=7 | eligible=7 | 10.7s
[1,180/1,478] L26_V358 | DONE | windows=7 | eligible=7 | 10.2s
[1,181/1,478] L26_V359 | DONE | windows=7 | eligible=7 | 10.9s
[1,182/1,478] L26_V360 | DONE | windows=7 | eligible=7 | 10.3s
[1,183/1,478] L26_V361 | DONE | windows=7 | eligible=7 | 10.1s
[1,184/1,478] L26_V362 | DONE | windows=7 | eligible=7 | 10.8s
[1,185/1,478] L26_V363 | DONE | windows=7 | eligible=7 | 10.6s
[1,186/1,478] L26_V364 | DONE | windows=7 | eligible=7 | 10.4s
[1,187/1,478] L26_V365 | DONE | windows=7 | eligible=7 | 11.3s
[1,188/1,478] L26_V366 | DONE | windows=7 | eligible=7 | 10.3s
[1,189/1,478] L26_V367 | DONE | windows=7 | eligible=7 | 11.0s
[1,190/1,478] L26_V368 | DONE | windows=7 | eligible=7 | 11.0s
[1,191/1,478] L26_V369 | DONE | windows=7 | eligible=7 | 10.4s
[1,192/1,478] L26_V370 | DONE | windows=7 | eligible=7 | 10.4s
[1,193/1,478] L26_V371 | DONE | windows=7 | eligible=7 | 11.0s
[1,194/1,478] L26_V372 | DONE | windows=7 | eligible=7 | 9.9s
[1,195/1,478] L26_V373 | DONE | windows=7 | eligible=7 | 10.5s
[1,196/1,478] L26_V374 | DONE | windows=7 | eligible=7 | 9.3s
[1,197/1,478] L26_V375 | DONE | windows=7 | eligible=7 | 7.7s
[1,198/1,478] L26_V376 | DONE | windows=7 | eligible=7 | 8.7s
[1,199/1,478] L26_V377 | DONE | windows=7 | eligible=7 | 7.8s
[1,200/1,478] L26_V378 | DONE | windows=7 | eligible=7 | 7.8s
[1,201/1,478] L26_V379 | DONE | windows=7 | eligible=7 | 7.8s
[1,202/1,478] L26_V380 | DONE | windows=7 | eligible=7 | 7.5s
[1,203/1,478] L26_V381 | DONE | windows=7 | eligible=7 | 9.5s
[1,204/1,478] L26_V382 | DONE | windows=7 | eligible=7 | 7.9s
[1,205/1,478] L26_V383 | DONE | windows=7 | eligible=7 | 8.2s
[1,206/1,478] L26_V384 | DONE | windows=7 | eligible=7 | 8.8s
[1,207/1,478] L26_V385 | DONE | windows=7 | eligible=7 | 9.4s
[1,208/1,478] L26_V386 | DONE | windows=7 | eligible=7 | 8.3s
[1,209/1,478] L26_V387 | DONE | windows=7 | eligible=7 | 7.4s
[1,210/1,478] L26_V388 | DONE | windows=7 | eligible=7 | 8.0s
[1,211/1,478] L26_V389 | DONE | windows=7 | eligible=7 | 8.7s
[1,212/1,478] L26_V390 | DONE | windows=7 | eligible=7 | 8.2s
[1,213/1,478] L26_V391 | DONE | windows=7 | eligible=7 | 8.3s
[1,214/1,478] L26_V392 | DONE | windows=7 | eligible=7 | 8.8s
[1,215/1,478] L26_V393 | DONE | windows=7 | eligible=7 | 8.6s
[1,216/1,478] L26_V394 | DONE | windows=7 | eligible=7 | 8.2s
[1,217/1,478] L26_V395 | DONE | windows=7 | eligible=7 | 8.1s
[1,218/1,478] L26_V396 | DONE | windows=7 | eligible=7 | 8.2s
[1,219/1,478] L26_V397 | DONE | windows=7 | eligible=7 | 8.5s
[1,220/1,478] L26_V398 | DONE | windows=7 | eligible=7 | 7.9s
[1,221/1,478] L26_V399 | DONE | windows=7 | eligible=7 | 9.5s
[1,222/1,478] L26_V400 | DONE | windows=7 | eligible=7 | 7.7s
[1,223/1,478] L26_V401 | DONE | windows=7 | eligible=7 | 7.9s
[1,224/1,478] L26_V402 | DONE | windows=7 | eligible=7 | 8.6s
[1,225/1,478] L26_V403 | DONE | windows=7 | eligible=7 | 7.9s
[1,226/1,478] L26_V404 | DONE | windows=7 | eligible=7 | 11.8s
[1,227/1,478] L26_V405 | DONE | windows=7 | eligible=7 | 9.2s
[1,228/1,478] L26_V406 | DONE | windows=7 | eligible=7 | 8.4s
[1,229/1,478] L26_V407 | DONE | windows=7 | eligible=7 | 8.0s
[1,230/1,478] L26_V408 | DONE | windows=7 | eligible=7 | 9.4s
[1,231/1,478] L26_V409 | DONE | windows=7 | eligible=7 | 7.8s
[1,232/1,478] L26_V410 | DONE | windows=7 | eligible=7 | 8.6s
[1,233/1,478] L26_V411 | DONE | windows=7 | eligible=7 | 8.4s
[1,234/1,478] L26_V412 | DONE | windows=7 | eligible=7 | 7.9s
[1,235/1,478] L26_V413 | DONE | windows=7 | eligible=7 | 7.6s
[1,236/1,478] L26_V414 | DONE | windows=7 | eligible=7 | 7.7s
[1,237/1,478] L26_V415 | DONE | windows=7 | eligible=7 | 8.3s
[1,238/1,478] L26_V416 | DONE | windows=7 | eligible=7 | 8.1s
[1,239/1,478] L26_V418 | DONE | windows=7 | eligible=7 | 7.9s
[1,240/1,478] L26_V419 | DONE | windows=7 | eligible=7 | 8.0s
[1,241/1,478] L26_V420 | DONE | windows=7 | eligible=7 | 8.3s
[1,242/1,478] L26_V421 | DONE | windows=7 | eligible=7 | 8.5s
[1,243/1,478] L26_V422 | DONE | windows=7 | eligible=7 | 8.6s
[1,244/1,478] L26_V423 | DONE | windows=7 | eligible=7 | 7.4s
[1,245/1,478] L26_V424 | DONE | windows=7 | eligible=7 | 8.0s
[1,246/1,478] L26_V425 | DONE | windows=7 | eligible=7 | 7.6s
[1,247/1,478] L26_V426 | DONE | windows=7 | eligible=7 | 8.9s
[1,248/1,478] L26_V427 | DONE | windows=7 | eligible=7 | 7.6s
[1,249/1,478] L26_V428 | DONE | windows=8 | eligible=8 | 9.5s
[1,250/1,478] L26_V429 | DONE | windows=8 | eligible=8 | 9.6s
[1,251/1,478] L26_V430 | DONE | windows=8 | eligible=8 | 7.9s
[1,252/1,478] L26_V431 | DONE | windows=7 | eligible=7 | 9.0s
[1,253/1,478] L26_V432 | DONE | windows=7 | eligible=7 | 8.4s
[1,254/1,478] L26_V433 | DONE | windows=8 | eligible=8 | 8.4s
[1,255/1,478] L26_V434 | DONE | windows=8 | eligible=8 | 8.9s
[1,256/1,478] L26_V435 | DONE | windows=8 | eligible=8 | 9.3s
[1,257/1,478] L26_V436 | DONE | windows=8 | eligible=8 | 8.7s
[1,258/1,478] L26_V437 | DONE | windows=7 | eligible=7 | 9.1s
[1,259/1,478] L26_V438 | DONE | windows=7 | eligible=7 | 8.1s
[1,260/1,478] L26_V439 | DONE | windows=8 | eligible=8 | 9.2s
[1,261/1,478] L26_V440 | DONE | windows=8 | eligible=8 | 9.6s
[1,262/1,478] L26_V441 | DONE | windows=7 | eligible=7 | 9.0s
[1,263/1,478] L26_V442 | DONE | windows=8 | eligible=8 | 7.9s
[1,264/1,478] L26_V443 | DONE | windows=8 | eligible=8 | 9.3s
[1,265/1,478] L26_V444 | DONE | windows=7 | eligible=7 | 8.4s
[1,266/1,478] L26_V445 | DONE | windows=8 | eligible=8 | 8.8s
[1,267/1,478] L26_V446 | DONE | windows=7 | eligible=7 | 8.5s
[1,268/1,478] L26_V447 | DONE | windows=7 | eligible=7 | 8.1s
[1,269/1,478] L26_V448 | DONE | windows=7 | eligible=7 | 9.7s
[1,270/1,478] L26_V449 | DONE | windows=7 | eligible=7 | 9.3s
[1,271/1,478] L26_V450 | DONE | windows=8 | eligible=8 | 9.0s
[1,272/1,478] L26_V451 | DONE | windows=7 | eligible=7 | 9.2s
[1,273/1,478] L26_V452 | DONE | windows=7 | eligible=7 | 8.6s
[1,274/1,478] L26_V453 | DONE | windows=8 | eligible=8 | 8.5s
[1,275/1,478] L26_V454 | DONE | windows=7 | eligible=7 | 9.1s
[1,276/1,478] L26_V455 | DONE | windows=8 | eligible=8 | 9.1s
[1,277/1,478] L26_V456 | DONE | windows=8 | eligible=8 | 9.2s
[1,278/1,478] L26_V457 | DONE | windows=8 | eligible=8 | 9.3s
[1,279/1,478] L26_V458 | DONE | windows=7 | eligible=7 | 7.8s
[1,280/1,478] L26_V459 | DONE | windows=7 | eligible=7 | 7.7s
[1,281/1,478] L26_V460 | DONE | windows=7 | eligible=7 | 7.5s
[1,282/1,478] L26_V461 | DONE | windows=7 | eligible=7 | 7.7s
[1,283/1,478] L26_V462 | DONE | windows=7 | eligible=7 | 9.2s
[1,284/1,478] L26_V463 | DONE | windows=7 | eligible=7 | 7.9s
[1,285/1,478] L26_V464 | DONE | windows=7 | eligible=7 | 8.2s
[1,286/1,478] L26_V465 | DONE | windows=7 | eligible=7 | 8.6s
[1,287/1,478] L26_V466 | DONE | windows=7 | eligible=7 | 8.0s
[1,288/1,478] L26_V467 | DONE | windows=7 | eligible=7 | 9.0s
[1,289/1,478] L26_V468 | DONE | windows=7 | eligible=7 | 8.5s
[1,290/1,478] L26_V469 | DONE | windows=7 | eligible=7 | 8.2s
[1,291/1,478] L26_V470 | DONE | windows=7 | eligible=7 | 8.3s
[1,292/1,478] L26_V471 | DONE | windows=7 | eligible=7 | 7.8s
[1,293/1,478] L26_V472 | DONE | windows=7 | eligible=7 | 8.0s
[1,294/1,478] L26_V473 | DONE | windows=7 | eligible=7 | 8.0s
[1,295/1,478] L26_V474 | DONE | windows=7 | eligible=7 | 7.8s
[1,296/1,478] L26_V475 | DONE | windows=7 | eligible=7 | 7.7s
[1,297/1,478] L26_V476 | DONE | windows=7 | eligible=7 | 8.2s
[1,298/1,478] L26_V477 | DONE | windows=7 | eligible=7 | 8.1s
[1,299/1,478] L26_V478 | DONE | windows=7 | eligible=7 | 8.1s
[1,300/1,478] L26_V479 | DONE | windows=7 | eligible=7 | 8.0s
[1,301/1,478] L26_V480 | DONE | windows=7 | eligible=7 | 8.8s
[1,302/1,478] L26_V481 | DONE | windows=7 | eligible=7 | 9.1s
[1,303/1,478] L26_V482 | DONE | windows=7 | eligible=7 | 9.0s
[1,304/1,478] L26_V483 | DONE | windows=7 | eligible=7 | 8.8s
[1,305/1,478] L26_V484 | DONE | windows=7 | eligible=7 | 8.6s
[1,306/1,478] L26_V485 | DONE | windows=7 | eligible=7 | 7.9s
[1,307/1,478] L26_V486 | DONE | windows=7 | eligible=7 | 8.1s
[1,308/1,478] L26_V487 | DONE | windows=7 | eligible=7 | 7.9s
[1,309/1,478] L26_V488 | DONE | windows=7 | eligible=7 | 8.5s
[1,310/1,478] L26_V489 | DONE | windows=7 | eligible=7 | 7.8s
[1,311/1,478] L26_V490 | DONE | windows=7 | eligible=7 | 8.5s
[1,312/1,478] L26_V491 | DONE | windows=7 | eligible=7 | 8.3s
[1,313/1,478] L26_V492 | DONE | windows=7 | eligible=7 | 8.1s
[1,314/1,478] L26_V493 | DONE | windows=7 | eligible=7 | 8.4s
[1,315/1,478] L26_V494 | DONE | windows=7 | eligible=7 | 7.9s
[1,316/1,478] L26_V495 | DONE | windows=7 | eligible=7 | 8.2s
[1,317/1,478] L26_V496 | DONE | windows=7 | eligible=7 | 9.3s
[1,318/1,478] L26_V497 | DONE | windows=7 | eligible=7 | 8.2s
[1,319/1,478] L26_V498 | DONE | windows=7 | eligible=7 | 8.5s
[1,320/1,478] L26_V499 | DONE | windows=7 | eligible=7 | 8.4s
[1,321/1,478] L27_V001 | DONE | windows=13 | eligible=13 | 13.6s
[1,322/1,478] L27_V002 | DONE | windows=13 | eligible=13 | 13.9s
[1,323/1,478] L27_V003 | DONE | windows=13 | eligible=13 | 14.0s
[1,324/1,478] L27_V004 | DONE | windows=14 | eligible=14 | 14.6s
[1,325/1,478] L27_V005 | DONE | windows=14 | eligible=14 | 13.9s
[1,326/1,478] L27_V006 | DONE | windows=13 | eligible=13 | 13.8s
[1,327/1,478] L27_V007 | DONE | windows=14 | eligible=14 | 14.4s
[1,328/1,478] L27_V008 | DONE | windows=14 | eligible=14 | 14.4s
[1,329/1,478] L27_V009 | DONE | windows=13 | eligible=13 | 14.0s
[1,330/1,478] L27_V010 | DONE | windows=13 | eligible=13 | 14.1s
[1,331/1,478] L27_V011 | DONE | windows=13 | eligible=13 | 14.2s
[1,332/1,478] L27_V012 | DONE | windows=14 | eligible=14 | 14.1s
[1,333/1,478] L27_V013 | DONE | windows=13 | eligible=13 | 14.4s
[1,334/1,478] L27_V014 | DONE | windows=13 | eligible=13 | 14.0s
[1,335/1,478] L27_V015 | DONE | windows=13 | eligible=13 | 13.7s
[1,336/1,478] L27_V016 | DONE | windows=13 | eligible=13 | 13.9s
[1,337/1,478] L28_V001 | DONE | windows=28 | eligible=28 | 27.5s
[1,338/1,478] L28_V002 | DONE | windows=26 | eligible=26 | 25.1s
[1,339/1,478] L28_V003 | DONE | windows=26 | eligible=26 | 23.8s
[1,340/1,478] L28_V004 | DONE | windows=25 | eligible=25 | 24.2s
[1,341/1,478] L28_V005 | DONE | windows=25 | eligible=25 | 24.8s
[1,342/1,478] L28_V006 | DONE | windows=25 | eligible=25 | 23.5s
[1,343/1,478] L28_V007 | DONE | windows=25 | eligible=25 | 23.3s
[1,344/1,478] L28_V008 | DONE | windows=25 | eligible=25 | 24.7s
[1,345/1,478] L28_V009 | DONE | windows=25 | eligible=25 | 23.3s
[1,346/1,478] L28_V010 | DONE | windows=25 | eligible=25 | 23.3s
[1,347/1,478] L28_V011 | DONE | windows=26 | eligible=26 | 24.7s
[1,348/1,478] L28_V012 | DONE | windows=25 | eligible=25 | 25.2s
[1,349/1,478] L28_V013 | DONE | windows=25 | eligible=25 | 23.8s
[1,350/1,478] L28_V014 | DONE | windows=25 | eligible=25 | 23.6s
[1,351/1,478] L28_V015 | DONE | windows=25 | eligible=25 | 24.8s
[1,352/1,478] L28_V016 | DONE | windows=26 | eligible=26 | 27.9s
[1,353/1,478] L28_V017 | DONE | windows=26 | eligible=26 | 26.4s
[1,354/1,478] L28_V018 | DONE | windows=25 | eligible=25 | 25.3s
[1,355/1,478] L28_V019 | DONE | windows=25 | eligible=25 | 23.8s
[1,356/1,478] L28_V020 | DONE | windows=25 | eligible=25 | 24.4s
[1,357/1,478] L28_V021 | DONE | windows=25 | eligible=25 | 25.9s
[1,358/1,478] L28_V022 | DONE | windows=25 | eligible=25 | 26.1s
[1,359/1,478] L28_V023 | DONE | windows=24 | eligible=24 | 22.2s
[1,360/1,478] L28_V024 | DONE | windows=25 | eligible=25 | 25.1s
[1,361/1,478] L29_V001 | DONE | windows=24 | eligible=24 | 27.6s
[1,362/1,478] L29_V002 | DONE | windows=23 | eligible=23 | 25.6s
[1,363/1,478] L29_V003 | DONE | windows=23 | eligible=23 | 25.2s
[1,364/1,478] L29_V004 | DONE | windows=24 | eligible=24 | 23.7s
[1,365/1,478] L29_V005 | DONE | windows=24 | eligible=24 | 23.2s
[1,366/1,478] L29_V006 | DONE | windows=24 | eligible=24 | 23.8s
[1,367/1,478] L29_V007 | DONE | windows=24 | eligible=24 | 23.4s
[1,368/1,478] L29_V008 | DONE | windows=24 | eligible=24 | 24.9s
[1,369/1,478] L29_V009 | DONE | windows=24 | eligible=24 | 24.5s
[1,370/1,478] L29_V010 | DONE | windows=24 | eligible=24 | 23.1s
[1,371/1,478] L29_V011 | DONE | windows=24 | eligible=24 | 23.2s
[1,372/1,478] L29_V012 | DONE | windows=24 | eligible=24 | 24.7s
[1,373/1,478] L29_V013 | DONE | windows=24 | eligible=24 | 25.1s
[1,374/1,478] L29_V014 | DONE | windows=23 | eligible=23 | 22.4s
[1,375/1,478] L29_V015 | DONE | windows=24 | eligible=24 | 23.7s
[1,376/1,478] L29_V016 | DONE | windows=24 | eligible=24 | 23.2s
[1,377/1,478] L29_V017 | DONE | windows=24 | eligible=24 | 23.9s
[1,378/1,478] L29_V018 | DONE | windows=25 | eligible=25 | 28.2s
[1,379/1,478] L29_V019 | DONE | windows=24 | eligible=24 | 23.9s
[1,380/1,478] L29_V020 | DONE | windows=24 | eligible=24 | 23.6s
[1,381/1,478] L29_V021 | DONE | windows=24 | eligible=24 | 23.4s
[1,382/1,478] L29_V022 | DONE | windows=24 | eligible=24 | 23.8s
[1,383/1,478] L29_V023 | DONE | windows=24 | eligible=24 | 26.8s
[1,384/1,478] L30_V001 | DONE | windows=3 | eligible=3 | 4.3s
[1,385/1,478] L30_V002 | DONE | windows=4 | eligible=4 | 5.9s
[1,386/1,478] L30_V003 | DONE | windows=7 | eligible=7 | 8.5s
[1,387/1,478] L30_V004 | DONE | windows=6 | eligible=6 | 6.7s
[1,388/1,478] L30_V005 | DONE | windows=2 | eligible=2 | 3.4s
[1,389/1,478] L30_V006 | DONE | windows=4 | eligible=4 | 5.6s
[1,390/1,478] L30_V007 | DONE | windows=7 | eligible=7 | 8.5s
[1,391/1,478] L30_V008 | DONE | windows=5 | eligible=5 | 5.7s
[1,392/1,478] L30_V009 | DONE | windows=10 | eligible=10 | 10.9s
[1,393/1,478] L30_V010 | DONE | windows=4 | eligible=4 | 6.0s
[1,394/1,478] L30_V011 | DONE | windows=2 | eligible=2 | 3.5s
[1,395/1,478] L30_V012 | DONE | windows=7 | eligible=7 | 8.4s
[1,396/1,478] L30_V013 | DONE | windows=2 | eligible=2 | 3.8s
[1,397/1,478] L30_V014 | DONE | windows=3 | eligible=3 | 4.0s
[1,398/1,478] L30_V015 | DONE | windows=6 | eligible=6 | 10.1s
[1,399/1,478] L30_V016 | DONE | windows=3 | eligible=3 | 5.6s
[1,400/1,478] L30_V017 | DONE | windows=7 | eligible=7 | 16.4s
[1,401/1,478] L30_V018 | DONE | windows=9 | eligible=9 | 10.2s
[1,402/1,478] L30_V019 | DONE | windows=4 | eligible=4 | 5.3s
[1,403/1,478] L30_V020 | DONE | windows=3 | eligible=3 | 4.9s
[1,404/1,478] L30_V021 | DONE | windows=3 | eligible=3 | 4.8s
[1,405/1,478] L30_V022 | DONE | windows=3 | eligible=3 | 3.7s
[1,406/1,478] L30_V023 | DONE | windows=5 | eligible=5 | 7.5s
[1,407/1,478] L30_V024 | DONE | windows=3 | eligible=3 | 3.8s
[1,408/1,478] L30_V025 | DONE | windows=6 | eligible=6 | 6.9s
[1,409/1,478] L30_V026 | DONE | windows=4 | eligible=4 | 4.9s
[1,410/1,478] L30_V027 | DONE | windows=8 | eligible=8 | 9.8s
[1,411/1,478] L30_V028 | DONE | windows=6 | eligible=6 | 7.0s
[1,412/1,478] L30_V029 | DONE | windows=7 | eligible=7 | 6.9s
[1,413/1,478] L30_V030 | DONE | windows=8 | eligible=8 | 8.4s
[1,414/1,478] L30_V031 | DONE | windows=3 | eligible=3 | 5.3s
[1,415/1,478] L30_V032 | DONE | windows=6 | eligible=6 | 6.9s
[1,416/1,478] L30_V033 | DONE | windows=8 | eligible=8 | 10.3s
[1,417/1,478] L30_V034 | DONE | windows=6 | eligible=6 | 6.8s
[1,418/1,478] L30_V035 | DONE | windows=2 | eligible=2 | 3.6s
[1,419/1,478] L30_V036 | DONE | windows=2 | eligible=2 | 3.2s
[1,420/1,478] L30_V037 | DONE | windows=5 | eligible=5 | 6.0s
[1,421/1,478] L30_V038 | DONE | windows=6 | eligible=6 | 7.9s
[1,422/1,478] L30_V039 | DONE | windows=6 | eligible=6 | 7.2s
[1,423/1,478] L30_V040 | DONE | windows=2 | eligible=2 | 4.2s
[1,424/1,478] L30_V041 | DONE | windows=2 | eligible=2 | 3.7s
[1,425/1,478] L30_V042 | DONE | windows=3 | eligible=3 | 3.7s
[1,426/1,478] L30_V043 | DONE | windows=4 | eligible=4 | 6.3s
[1,427/1,478] L30_V044 | DONE | windows=3 | eligible=3 | 4.9s
[1,428/1,478] L30_V045 | DONE | windows=7 | eligible=7 | 7.9s
[1,429/1,478] L30_V046 | DONE | windows=6 | eligible=6 | 7.6s
[1,430/1,478] L30_V047 | DONE | windows=7 | eligible=7 | 8.6s
[1,431/1,478] L30_V048 | DONE | windows=9 | eligible=9 | 10.4s
[1,432/1,478] L30_V050 | DONE | windows=3 | eligible=3 | 4.1s
[1,433/1,478] L30_V051 | DONE | windows=4 | eligible=4 | 5.9s
[1,434/1,478] L30_V052 | DONE | windows=7 | eligible=7 | 8.0s
[1,435/1,478] L30_V053 | DONE | windows=7 | eligible=7 | 7.8s
[1,436/1,478] L30_V054 | DONE | windows=8 | eligible=8 | 8.4s
[1,437/1,478] L30_V055 | DONE | windows=5 | eligible=5 | 7.1s
[1,438/1,478] L30_V056 | DONE | windows=7 | eligible=7 | 7.7s
[1,439/1,478] L30_V057 | DONE | windows=4 | eligible=4 | 5.1s
[1,440/1,478] L30_V058 | DONE | windows=3 | eligible=3 | 3.8s
[1,441/1,478] L30_V059 | DONE | windows=5 | eligible=5 | 6.2s
[1,442/1,478] L30_V060 | DONE | windows=3 | eligible=3 | 5.8s
[1,443/1,478] L30_V061 | DONE | windows=8 | eligible=8 | 8.2s
[1,444/1,478] L30_V062 | DONE | windows=5 | eligible=5 | 5.8s
[1,445/1,478] L30_V063 | DONE | windows=6 | eligible=6 | 6.7s
[1,446/1,478] L30_V064 | DONE | windows=6 | eligible=6 | 8.2s
[1,447/1,478] L30_V065 | DONE | windows=3 | eligible=3 | 3.6s
[1,448/1,478] L30_V066 | DONE | windows=6 | eligible=6 | 7.8s
[1,449/1,478] L30_V067 | DONE | windows=3 | eligible=3 | 3.6s
[1,450/1,478] L30_V068 | DONE | windows=6 | eligible=6 | 8.0s
[1,451/1,478] L30_V069 | DONE | windows=5 | eligible=5 | 6.5s
[1,452/1,478] L30_V070 | DONE | windows=2 | eligible=2 | 3.2s
[1,453/1,478] L30_V071 | DONE | windows=2 | eligible=2 | 3.3s
[1,454/1,478] L30_V072 | DONE | windows=2 | eligible=2 | 3.5s
[1,455/1,478] L30_V073 | DONE | windows=5 | eligible=5 | 6.3s
[1,456/1,478] L30_V074 | DONE | windows=6 | eligible=6 | 6.1s
[1,457/1,478] L30_V075 | DONE | windows=6 | eligible=6 | 6.2s
[1,458/1,478] L30_V076 | DONE | windows=4 | eligible=4 | 5.8s
[1,459/1,478] L30_V077 | DONE | windows=5 | eligible=5 | 5.4s
[1,460/1,478] L30_V078 | DONE | windows=5 | eligible=5 | 6.5s
[1,461/1,478] L30_V079 | DONE | windows=4 | eligible=4 | 5.5s
[1,462/1,478] L30_V080 | DONE | windows=6 | eligible=6 | 7.1s
[1,463/1,478] L30_V081 | DONE | windows=4 | eligible=4 | 5.8s
[1,464/1,478] L30_V082 | DONE | windows=5 | eligible=5 | 6.7s
[1,465/1,478] L30_V083 | DONE | windows=7 | eligible=7 | 8.9s
[1,466/1,478] L30_V084 | DONE | windows=5 | eligible=5 | 7.0s
[1,467/1,478] L30_V085 | DONE | windows=4 | eligible=4 | 5.0s
[1,468/1,478] L30_V086 | DONE | windows=4 | eligible=4 | 4.6s
[1,469/1,478] L30_V087 | DONE | windows=5 | eligible=5 | 7.6s
[1,470/1,478] L30_V088 | DONE | windows=5 | eligible=5 | 6.4s
[1,471/1,478] L30_V089 | DONE | windows=5 | eligible=5 | 5.6s
[1,472/1,478] L30_V090 | DONE | windows=5 | eligible=5 | 6.2s
[1,473/1,478] L30_V091 | DONE | windows=6 | eligible=6 | 7.3s
[1,474/1,478] L30_V092 | DONE | windows=4 | eligible=4 | 5.4s
[1,475/1,478] L30_V093 | DONE | windows=6 | eligible=6 | 7.5s
[1,476/1,478] L30_V094 | DONE | windows=5 | eligible=5 | 5.2s
[1,477/1,478] L30_V095 | DONE | windows=7 | eligible=7 | 7.6s
[1,478/1,478] L30_V096 | DONE | windows=2 | eligible=2 | 3.7s

Completed this run : 306
Corpus complete    : 1,476 / 1,478
Source failures    : 2

In [ ]:
# Read-only safety check after an interruption or Drive quota error.
# This does not load Parakeet and does not write anything to Drive.

status_rows, status_summary = scan_phase1(FULL_CORPUS_ROOT)
status_df                   = pd.DataFrame(status_rows)

transcript_root = FULL_CORPUS_ROOT / "phase1" / "transcripts"
canonical_root  = FULL_CORPUS_ROOT / "phase1" / "canonical_audio"
temp_audio_root = FULL_CORPUS_ROOT / "phase1" / "window_audio_tmp"

invalid_df = status_df[status_df["classification"] == "invalid_artifact"]
partial_df = status_df[status_df["classification"] == "partial"]
zero_byte  = [path for path in transcript_root.glob("*.json") if path.stat().st_size == 0]

print("Phase 1 saved state")
print("-------------------")
print(f"Complete videos : {status_summary['complete_videos']:,} / {status_summary['total_expected_videos']:,}")
print(f"Partial videos  : {status_summary['partial_videos']:,}")
print(f"Missing videos  : {status_summary['missing_videos']:,}")
print(f"Invalid files   : {status_summary['invalid_artifacts']:,}")
print(f"Failed windows  : {status_summary['failed_windows']:,}")
print(f"Physical windows: {status_summary['physical_windows']:,}")
print(f"Eligible windows: {status_summary['eligible_windows']:,}")
print(f"Extra JSON files: {len(status_summary['extra_transcript_artifact_ids']):,}")
print(f"Zero-byte JSONs : {len(zero_byte):,}")

print("\nInterrupted area")
focus_ids = ["L26_V348", "L26_V349", "L26_V350", "L26_V351"]
focus_columns = [
    "video_id", "classification", "complete", "window_count",
    "eligible_windows", "failed_windows", "invalid_reason",
]
display(status_df[status_df["video_id"].isin(focus_ids)][focus_columns].reset_index(drop = True))

print("Phase 1 storage currently visible on Drive")
for label, path in [
    ("transcripts", transcript_root),
    ("canonical_audio", canonical_root),
    ("window_audio_tmp", temp_audio_root),
] :
    size_bytes = sum(item.stat().st_size for item in path.rglob("*") if item.is_file()) if path.exists() else 0
    file_count = sum(1 for item in path.rglob("*") if item.is_file()) if path.exists() else 0
    print(f"{label:18s}: {file_count:,} files | {size_bytes / 1024**3:,.3f} GiB")

storage_safe = (
    status_summary["complete_videos"] >= 1_173
    and status_summary["invalid_artifacts"] == 0
    and not status_summary["extra_transcript_artifact_ids"]
    and not zero_byte
)

print()
print("Saved checkpoint check:", "PASS" if storage_safe else "REVIEW REQUIRED")

if (not invalid_df.empty) :
    print("\nInvalid transcript artifacts:")
    display(invalid_df[focus_columns].head(50))

if (not partial_df.empty) :
    print("\nValid partial checkpoints:")
    display(partial_df[focus_columns].head(50))

Phase 1 saved state
-------------------
Complete videos : 1,476 / 1,478
Partial videos  : 1
Missing videos  : 1
Invalid files   : 0
Failed windows  : 0
Physical windows: 26,128
Eligible windows: 26,082
Extra JSON files: 0
Zero-byte JSONs : 0

Interrupted area

,video_id,classification,complete,window_count,eligible_windows,failed_windows,invalid_reason
0,L26_V348,complete_clean,True,7,7,0,None
1,L26_V349,complete_clean,True,7,7,0,None
2,L26_V350,complete_clean,True,7,7,0,None
3,L26_V351,complete_clean,True,7,7,0,None

Phase 1 storage currently visible on Drive
transcripts       : 1,477 files | 0.194 GiB
canonical_audio   : 2 files | 0.082 GiB
window_audio_tmp  : 1 files | 0.002 GiB

Saved checkpoint check: PASS

Valid partial checkpoints:

,video_id,classification,complete,window_count,eligible_windows,failed_windows,invalid_reason
739,L25_V007,partial,False,53,53,0,None

In [ ]:
# Fast reconnect check: reads saved transcript JSON only. No Parakeet model load and no source hashing.
status_rows, status_summary = scan_phase1(FULL_CORPUS_ROOT)

print("Complete        :", f"{status_summary['complete_videos']:,} / {status_summary['total_expected_videos']:,}")
print("Partial         :", f"{status_summary['partial_videos']:,}")
print("Missing         :", f"{status_summary['missing_videos']:,}")
print("Invalid         :", f"{status_summary['invalid_artifacts']:,}")
print("Failed windows  :", f"{status_summary['failed_windows']:,}")
print("Empty OK windows:", f"{status_summary['empty_ok_windows']:,}")
print("Eligible windows:", f"{status_summary['eligible_windows']:,}")
display(pd.DataFrame(status_summary["classification_counts"].items(), columns = ["classification", "videos"]))

Complete        : 1,476 / 1,478
Partial         : 1
Missing         : 1
Invalid         : 0
Failed windows  : 0
Empty OK windows: 15
Eligible windows: 26,082

                classification  videos
0               complete_clean    1466
1  complete_with_empty_windows      10
2                      missing       1
3                      partial       1

In [ ]:
# Full Phase 1 verification against the actual source videos.
# Read-only: no ASR model load and no transcript files are modified.

from asr_retrieval.audio import build_physical_windows, probe_video, select_audio_stream
from full_corpus import inspect_source_inventory
from tqdm.auto import tqdm

inventory_rows, inventory_summary = load_inventory(FULL_CORPUS_ROOT)
status_rows, status_summary       = scan_phase1(FULL_CORPUS_ROOT)
offline_config                    = make_offline_config(FULL_CORPUS_ROOT)

# Recheck the actual 1,478 MP4 files, sizes, mtimes and FPS values.
current_inventory_rows, current_inventory_summary = inspect_source_inventory(VIDEO_ROOT, FPS_MAP_PATH)

if (not current_inventory_summary["passed"]) :
    raise RuntimeError("Current source inventory failed validation.")

if (current_inventory_summary["inventory_identity"] != inventory_summary["inventory_identity"]) :
    raise RuntimeError("Current source inventory no longer matches the frozen inventory.")

status_by_id    = {row["video_id"] : row for row in status_rows}
validation_rows = []
probe_errors    = []

for inventory_row in tqdm(inventory_rows, desc = "Validating videos", unit = "video", dynamic_ncols = True) :
    video_id        = inventory_row["video_id"]
    source_path     = Path(inventory_row["source_path"])
    status          = status_by_id[video_id]
    transcript_path = FULL_CORPUS_ROOT / "phase1" / "transcripts" / f"{video_id}.json"

    video_duration_s = None
    audio_duration_s = None
    probe_error      = None

    try :
        probe        = probe_video(source_path)
        audio_stream = select_audio_stream(probe)

        raw_video_duration = probe.get("format", {}).get("duration")
        raw_audio_duration = audio_stream.get("duration")

        if (raw_video_duration not in {None, "N/A"}) :
            video_duration_s = float(raw_video_duration)

        if (raw_audio_duration not in {None, "N/A"}) :
            audio_duration_s = float(raw_audio_duration)
    except Exception as error :
        probe_error = f"{type(error).__name__}: {error}"
        probe_errors.append({"video_id" : video_id, "error" : probe_error})

    saved_source_duration_s = None
    canonical_duration_s    = None
    observed_windows        = int(status["window_count"])
    expected_windows_exact  = None

    if (status["artifact_exists"] and status["classification"] != "invalid_artifact") :
        payload         = read_json(transcript_path)
        video_metadata  = payload["video"]
        canonical_audio = payload["canonical_audio"]

        saved_source_duration_s = video_metadata.get("source_duration_s")
        sample_rate             = int(canonical_audio["sample_rate"])
        sample_count            = int(canonical_audio["sample_count"])
        canonical_duration_s    = sample_count / sample_rate
        expected_windows_exact  = len(build_physical_windows(video_id, sample_count, offline_config.audio))

    duration_reference_s = audio_duration_s if audio_duration_s is not None else video_duration_s
    expected_windows_probe = None

    if (duration_reference_s is not None and duration_reference_s > 0.0) :
        estimated_samples      = max(1, round(duration_reference_s * offline_config.audio.sample_rate))
        expected_windows_probe = len(build_physical_windows(video_id, estimated_samples, offline_config.audio))

    exact_window_match = (
        observed_windows == expected_windows_exact
        if status["complete"] and expected_windows_exact is not None
        else observed_windows <= expected_windows_exact
        if expected_windows_exact is not None
        else None
    )

    saved_duration_match = None
    if (saved_source_duration_s is not None and video_duration_s is not None) :
        saved_duration_match = abs(float(saved_source_duration_s) - video_duration_s) <= 0.1

    duration_gap_s   = None
    duration_close   = None
    duration_tolerance_s = None

    if (canonical_duration_s is not None and duration_reference_s is not None) :
        duration_gap_s       = abs(canonical_duration_s - duration_reference_s)
        duration_tolerance_s = max(2.0, 0.01 * duration_reference_s)
        duration_close       = duration_gap_s <= duration_tolerance_s

    validation_rows.append({
        "video_id"                  : video_id,
        "classification"            : status["classification"],
        "complete"                  : status["complete"],
        "video_duration_s"          : video_duration_s,
        "audio_duration_s"          : audio_duration_s,
        "canonical_duration_s"      : canonical_duration_s,
        "observed_windows"          : observed_windows,
        "expected_windows_exact"    : expected_windows_exact,
        "expected_windows_probe"    : expected_windows_probe,
        "exact_window_match"        : exact_window_match,
        "saved_duration_match"      : saved_duration_match,
        "duration_gap_s"            : duration_gap_s,
        "duration_close"            : duration_close,
        "eligible_windows"          : status["eligible_windows"],
        "failed_windows"            : status["failed_windows"],
        "empty_ok_windows"          : status["ok_empty_windows"],
        "probe_error"               : probe_error,
        "invalid_reason"            : status["invalid_reason"],
    })

validation_df = pd.DataFrame(validation_rows)

invalid_ids  = validation_df.loc[validation_df["classification"] == "invalid_artifact", "video_id"].tolist()
recovery_ids = validation_df.loc[~validation_df["complete"] & (validation_df["classification"] != "invalid_artifact"), "video_id"].tolist()
failed_ids   = validation_df.loc[validation_df["failed_windows"] > 0, "video_id"].tolist()

exact_window_errors = validation_df[
    validation_df["complete"]
    & validation_df["exact_window_match"].eq(False)
]

duration_review_df = validation_df[
    validation_df["complete"]
    & validation_df["duration_close"].eq(False)
]

print("Full Phase 1 verification")
print("-------------------------")
print(f"Inventory match      : PASS")
print(f"Expected videos      : {len(inventory_rows):,}")
print(f"Complete             : {status_summary['complete_videos']:,}")
print(f"Partial              : {status_summary['partial_videos']:,}")
print(f"Missing              : {status_summary['missing_videos']:,}")
print(f"Invalid artifacts    : {len(invalid_ids):,}")
print(f"Exact window errors  : {len(exact_window_errors):,}")
print(f"FFprobe errors       : {len(probe_errors):,}")
print(f"Duration reviews     : {len(duration_review_df):,}")
print(f"Failed ASR videos    : {len(failed_ids):,}")
print(f"Need transcription   : {len(recovery_ids):,}")

print("\nWindow-count distribution")
window_distribution = (
    validation_df[validation_df["complete"]]
    .groupby("observed_windows")
    .agg(
        videos                = ("video_id", "count"),
        min_video_duration_s  = ("video_duration_s", "min"),
        max_video_duration_s  = ("video_duration_s", "max"),
        min_audio_duration_s  = ("canonical_duration_s", "min"),
        max_audio_duration_s  = ("canonical_duration_s", "max"),
    )
    .reset_index()
    .sort_values("observed_windows")
)
display(window_distribution)

print("\nVideos with 7 or fewer windows")
low_window_df = validation_df[
    validation_df["complete"] & (validation_df["observed_windows"] <= 7)
][[
    "video_id",
    "video_duration_s",
    "audio_duration_s",
    "canonical_duration_s",
    "observed_windows",
    "expected_windows_exact",
    "expected_windows_probe",
    "exact_window_match",
]]
display(low_window_df.sort_values(["observed_windows", "video_id"]).reset_index(drop = True))

if (recovery_ids) :
    print("\nVideos that still need transcription:")
    display(validation_df[validation_df["video_id"].isin(recovery_ids)][[
        "video_id", "classification", "observed_windows", "expected_windows_exact", "probe_error", "invalid_reason"
    ]].reset_index(drop = True))

if (invalid_ids) :
    print("\nINVALID artifacts – do not automatically overwrite these:")
    display(validation_df[validation_df["video_id"].isin(invalid_ids)][[
        "video_id", "classification", "invalid_reason"
    ]].reset_index(drop = True))

if (not exact_window_errors.empty) :
    print("\nExact window-count mismatches:")
    display(exact_window_errors)

if (duration_review_df.shape[0] > 0) :
    print("\nSource/audio duration differences to review:")
    display(duration_review_df[[
        "video_id", "video_duration_s", "audio_duration_s", "canonical_duration_s",
        "observed_windows", "expected_windows_exact", "duration_gap_s"
    ]].sort_values("duration_gap_s", ascending = False).head(50))

validation_passed = (
    current_inventory_summary["inventory_identity"] == inventory_summary["inventory_identity"]
    and not invalid_ids
    and exact_window_errors.empty
    and not probe_errors
)

print()
print("Structural + source verification:", "PASS" if validation_passed else "REVIEW REQUIRED")

Validating videos:   0%|          | 0/1478 [00:00<?, ?video/s]

Full Phase 1 verification
-------------------------
Inventory match      : PASS
Expected videos      : 1,478
Complete             : 1,476
Partial              : 1
Missing              : 1
Invalid artifacts    : 0
Exact window errors  : 0
FFprobe errors       : 0
Duration reviews     : 0
Failed ASR videos    : 0
Need transcription   : 2

Window-count distribution

,observed_windows,videos,min_video_duration_s,max_video_duration_s,min_audio_duration_s,max_audio_duration_s
0,1,4,32.555,37.779,32.554375,37.778875
1,2,12,65.179,97.222,65.178438,97.221937
2,3,16,107.718,147.633,107.717375,147.632500
3,4,16,160.172,194.978,160.171250,194.978000
4,5,17,197.881,235.335,197.880437,235.334250
5,6,24,240.141,282.425,240.140813,282.424312
6,7,472,287.580,329.910,287.579125,329.909125
7,8,49,330.026,371.497,330.025250,371.496062
8,9,10,375.142,417.054,375.141625,417.053625
9,10,2,421.698,435.537,421.697625,435.536688
10,11,4,468.742,508.053,468.741250,508.052625
11,12,8,517.457,554.493,517.456688,554.492500
12,13,26,556.397,598.495,556.396562,598.494312
13,14,8,600.631,638.874,600.630562,638.873812
14,15,5,645.120,688.101,645.120000,688.100125
15,16,2,702.985,715.872,702.984125,715.871188
16,17,3,763.171,778.333,763.170250,778.332875
17,18,4,798.163,824.634,798.162750,824.633500
18,19,8,825.214,868.218,825.214000,868.217313
19,20,17,871.027,914.449,871.026938,914.448250
20,21,28,916.794,957.545,916.793500,957.544500
21,22,38,962.352,1004.937,962.351000,1004.936438
22,23,62,1005.192,1049.937,1005.191875,1049.936688
23,24,83,1052.073,1094.171,1052.072938,1094.170687
24,25,108,1095.541,1139.891,1095.540688,1139.890813
25,26,91,1140.286,1184.984,1140.285562,1184.983937
26,27,116,1185.054,1229.869,1185.053625,1229.868125
27,28,78,1231.448,1274.730,1231.447062,1274.729063
28,29,48,1275.728,1319.892,1275.727562,1319.891875
29,30,39,1321.262,1362.129,1321.261875,1362.129000
30,31,22,1365.845,1406.549,1365.844188,1406.548750
31,32,12,1415.025,1448.183,1415.024062,1448.182125
32,33,6,1456.101,1499.058,1456.100125,1499.057063
33,34,4,1501.124,1533.144,1501.123625,1533.143937
34,35,2,1554.507,1582.812,1554.506312,1582.811438
35,36,6,1591.287,1634.685,1591.286750,1634.684812
36,37,4,1639.840,1662.433,1639.839625,1662.432687
37,38,2,1686.768,1695.313,1686.767188,1695.312125
38,39,2,1736.180,1755.383,1736.179250,1755.382125
39,40,3,1779.137,1809.624,1779.136125,1809.623938
40,42,2,1875.685,1893.797,1875.684750,1893.796313
41,43,5,1908.588,1938.542,1908.587375,1938.541125
42,45,1,2017.257,2017.257,2017.256813,2017.256813
43,46,1,2070.710,2070.710,2070.709125,2070.709125
44,48,1,2163.938,2163.938,2163.937250,2163.937250
45,49,2,2189.456,2204.689,2189.456000,2204.688250
46,51,2,2267.174,2291.485,2267.173188,2291.484437
47,56,1,2518.205,2518.205,2518.204062,2518.204062

Videos with 7 or fewer windows

,video_id,video_duration_s,audio_duration_s,canonical_duration_s,observed_windows,expected_windows_exact,expected_windows_probe,exact_window_match
0,L24_V040,37.779,37.778866,37.778875,1,1.0,1,True
1,L24_V041,35.852,35.851610,35.851625,1,1.0,1,True
2,L24_V044,35.341,35.340771,35.340812,1,1.0,1,True
3,L24_V045,32.555,32.554376,32.554375,1,1.0,1,True
4,L24_V012,97.222,97.221950,97.221937,2,2.0,2,True
...,...,...,...,...,...,...,...,...
556,L30_V052,292.758,292.757188,292.757187,7,7.0,7,True
557,L30_V053,304.368,304.367166,304.367188,7,7.0,7,True
558,L30_V056,300.351,300.350113,300.350125,7,7.0,7,True
559,L30_V083,297.425,297.424399,297.424438,7,7.0,7,True
560,L30_V095,309.615,309.614875,309.614875,7,7.0,7,True

Videos that still need transcription:

,video_id,classification,observed_windows,expected_windows_exact,probe_error,invalid_reason
0,K19_V003,missing,0,NaN,None,None
1,L25_V007,partial,53,61.0,None,None

Structural + source verification: PASS

In [ ]:
# Recover only unfinished videos.
# Clear stale locks only when no other transcription worker is running.

if (invalid_ids) :
    raise RuntimeError(f"Invalid transcript artifacts require manual review first: {invalid_ids}")

if (probe_errors) :
    raise RuntimeError(f"Source probe errors require review first: {probe_errors[ : 10]}")

LOCK_ROOT = FULL_CORPUS_ROOT / "phase1" / "locks"

recovery_lock_paths = [
    LOCK_ROOT / f"{video_id}.lock"
    for video_id in recovery_ids
    if (LOCK_ROOT / f"{video_id}.lock").exists()
]

print("Videos needing transcription:", recovery_ids)
print("Locks blocking recovery      :", len(recovery_lock_paths))

for lock_path in recovery_lock_paths :
    print(f"{lock_path.stem}: {lock_path.read_text(encoding = 'utf-8', errors = 'replace')}")

CLEAR_STALE_LOCKS = True  # Only when no other Colab/account is transcribing.

if (recovery_lock_paths and not CLEAR_STALE_LOCKS) :
    raise RuntimeError("Stale locks were found. Confirm no transcription worker is active before clearing them.")

for lock_path in recovery_lock_paths :
    lock_path.unlink()
    print("Removed stale lock:", lock_path.name)

if (recovery_ids) :
    recovery_report = transcribe_corpus(
        artifact_root = FULL_CORPUS_ROOT,
        video_ids     = recovery_ids,
    )
else :
    print("No missing or partial videos need transcription.")

Videos needing transcription: ['K19_V003', 'L25_V007']
Locks blocking recovery      : 2
K19_V003: {"pid": 16578, "host": "54052b8ea5e2", "created_at_utc": "2026-08-18T07:51:54.200657+00:00"}
L25_V007: {"pid": 3124, "host": "f333ed127747", "created_at_utc": "2026-08-18T09:11:15.380051+00:00"}
Removed stale lock: K19_V003.lock
Removed stale lock: L25_V007.lock
Corpus complete : 1,476 / 1,478
Selected        : 2
Skipped         : 0
To process      : 2
Loading Parakeet...
Loaded: nvidia/parakeet-ctc-0.6b-Vietnamese @ b0493142b49458810324e3db8be9e8e07b4ebc17
[    1/2] K19_V003 | DONE | windows=27 | eligible=27 | 24.1s
[    2/2] L25_V007 | DONE | windows=61 | eligible=61 | 14.3s

Completed this run : 2
Corpus complete    : 1,478 / 1,478
Source failures    : 0

In [ ]:
status_rows, status_summary = scan_phase1(FULL_CORPUS_ROOT)
status_df                   = pd.DataFrame(status_rows)

print("Complete       :", f"{status_summary['complete_videos']:,} / {status_summary['total_expected_videos']:,}")
print("Partial        :", f"{status_summary['partial_videos']:,}")
print("Missing        :", f"{status_summary['missing_videos']:,}")
print("Invalid        :", f"{status_summary['invalid_artifacts']:,}")
print("Failed windows :", f"{status_summary['failed_windows']:,}")
print("Empty OK       :", f"{status_summary['empty_ok_windows']:,}")
print("Eligible       :", f"{status_summary['eligible_windows']:,}")

remaining_df = status_df[
    (~status_df["complete"])
    | (status_df["classification"] == "invalid_artifact")
    | (status_df["failed_windows"] > 0)
]

if (not remaining_df.empty) :
    display(remaining_df.reset_index(drop = True))
    raise RuntimeError("Phase 1 is not fully clean yet.")

print("Phase 1 corpus verification: PASS")

Complete       : 1,478 / 1,478
Partial        : 0
Missing        : 0
Invalid        : 0
Failed windows : 0
Empty OK       : 15
Eligible       : 26,117
Phase 1 corpus verification: PASS

### Audit and retries

Audit the complete Phase 1 workspace, retry failed ASR windows, and only retry empty successful windows when you have explicitly reviewed those videos. Silence and non-speech can legitimately produce empty transcripts.

In [ ]:
audit_rows, failed_window_rows, phase1_summary = audit_phase1(FULL_CORPUS_ROOT)

print(json.dumps(phase1_summary, ensure_ascii = False, indent = 2))
if (failed_window_rows) :
    display(pd.DataFrame(failed_window_rows).head(100))
else :
    print("No failed ASR windows found.")

{
  "inventory_identity": "466408aa4d89e7e0412def939a5281081c17dfa1c151f8bf34e4538e7e1b23b4",
  "total_expected_videos": 1478,
  "complete_videos": 1478,
  "partial_videos": 0,
  "missing_videos": 0,
  "invalid_artifacts": 0,
  "failed_windows": 0,
  "empty_ok_windows": 15,
  "eligible_windows": 26117,
  "physical_windows": 26163,
  "extra_transcript_artifact_ids": [],
  "classification_counts": {
    "complete_clean": 1468,
    "complete_with_empty_windows": 10
  },
  "created_at_utc": "2026-08-18T20:07:57.276803+00:00",
  "passed": true
}
No failed ASR windows found.

In [ ]:
failed_video_ids = sorted({row["video_id"] for row in failed_window_rows})

if (failed_video_ids) :
    print(f"Retrying failed windows in {len(failed_video_ids):,} videos...")
    retry_report = transcribe_corpus(
        artifact_root = FULL_CORPUS_ROOT,
        video_ids     = failed_video_ids,
        retry_failed  = True,
    )
    audit_rows, failed_window_rows, phase1_summary = audit_phase1(FULL_CORPUS_ROOT)
else :
    print("No failed ASR windows remain.")

print("Residual failed windows:", phase1_summary["failed_windows"])

No failed ASR windows remain.
Residual failed windows: 0

In [ ]:
# Add IDs here only after reviewing empty-window cases that should contain speech.
EMPTY_RETRY_VIDEO_IDS : list[str] = []

if (EMPTY_RETRY_VIDEO_IDS) :
    empty_retry_report = transcribe_corpus(
        artifact_root = FULL_CORPUS_ROOT,
        video_ids     = EMPTY_RETRY_VIDEO_IDS,
        retry_empty   = True,
    )
    audit_rows, failed_window_rows, phase1_summary = audit_phase1(FULL_CORPUS_ROOT)
else :
    print("No selective empty-window retry requested.")

No selective empty-window retry requested.

In [ ]:
ALLOW_RESIDUAL_FAILURES = False

acceptance = phase1_acceptance(
    artifact_root           = FULL_CORPUS_ROOT,
    allow_residual_failures = ALLOW_RESIDUAL_FAILURES,
)
print(json.dumps(acceptance, ensure_ascii = False, indent = 2))

{
  "schema_version": "1.0",
  "accepted_at_utc": "2026-08-18T20:08:15.284251+00:00",
  "inventory_identity": "466408aa4d89e7e0412def939a5281081c17dfa1c151f8bf34e4538e7e1b23b4",
  "inventory_verified_at_utc": "2026-08-18T20:08:01.912774+00:00",
  "total_expected_videos": 1478,
  "complete_videos": 1478,
  "physical_window_count": 26163,
  "eligible_window_count": 26117,
  "residual_failed_window_count": 0,
  "residual_failed_window_ids": [],
  "residual_failures_explicitly_accepted": false,
  "blockers": [],
  "passed": true
}

In [ ]:
from google.colab import runtime
runtime.unassign()

## 4. Phase 2 release

Phase 2 builds the immutable BM25 + E5 release from the accepted transcript artifacts.

Install the pinned retrieval stack below only after Phase 1 is finished. Because the notebook now runs everything in one Python process, **restart the Colab runtime once after this install**. All Phase 1 artifacts are already saved on Drive.

After the restart, rerun only the Drive/path cell in Section 1 and the **Import the corpus helpers** cell. Skip the Phase 1 `%pip` and NeMo runtime cells.

In [3]:
%pip install "transformers==4.52.0" "sentence-transformers==5.4.0" pytest

Collecting transformers==4.52.0
  Downloading transformers-4.52.0-py3-none-any.whl.metadata (38 kB)
Collecting sentence-transformers==5.4.0
  Downloading sentence_transformers-5.4.0-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: pytest in /usr/local/lib/python3.12/dist-packages (8.4.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers==4.52.0) (3.32.3)
Requirement already satisfied: huggingface-hub<1.0,>=0.30.0 in /usr/local/lib/python3.12/dist-packages (from transformers==4.52.0) (0.36.2)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.52.0) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers==4.52.0) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.52.0) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.52.0) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers==4.52.0) (2.32.4)
Collecting tokenizers<0.22,>=0.21 (from transformers==4.52.0)
  Downloading tokenizers-0.21.4-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers==4.52.0) (0.8.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers==4.52.0) (4.67.3)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers==5.4.0) (2.11.0+cu128)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers==5.4.0) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers==5.4.0) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers==5.4.0) (4.16.0)
Requirement already satisfied: iniconfig>=1 in /usr/local/lib/python3.12/dist-packages (from pytest) (2.3.0)
Requirement already satisfied: pluggy<2,>=1.5 in /usr/local/lib/python3.12/dist-packages (from pytest) (1.6.0)
Requirement already satisfied: pygments>=2.7.2 in /usr/local/lib/python3.12/dist-packages (from pytest) (2.20.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers==4.52.0) (2024.12.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers==4.52.0) (1.6.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers==5.4.0) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers==5.4.0) (3.6.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers==5.4.0) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers==5.4.0) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers==5.4.0) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers==5.4.0) (3.1.6)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers==5.4.0) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers==5.4.0) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers==5.4.0) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers==5.4.0) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers==5.4.0) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers==5.4.0) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers==5.4.0) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers==5.4.0) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers==5.4.0) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers==5.4.0) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers==5.4.0) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers==5.4.0) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers==5.4.0) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers==5.4.0) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers==5.4.0) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers==5.4.0) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers==5.4.0) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers==5.4.0) (12.8.90)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.52.0) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.52.0) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.52.0) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.52.0) (2026.7.22)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=1.11.0->sentence-transformers==5.4.0) (1.6.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers==5.4.0) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers==5.4.0) (3.0.3)
WARNING: The candidate selected for download or install is a yanked version: 'transformers' candidate (version 4.52.0 at https://files.pythonhosted.org/packages/07/4d/2af465e5d2ac7986c5f8440b473719fafabaf9f2a0cbdfa7d4b4362e1db3/transformers-4.52.0-py3-none-any.whl (from https://pypi.org/simple/transformers/) (requires-python:>=3.9.0))
Reason for being yanked: <none given>
Downloading transformers-4.52.0-py3-none-any.whl (10.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.5/10.5 MB 17.9 MB/s eta 0:00:00
Downloading sentence_transformers-5.4.0-py3-none-any.whl (570 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 570.8/570.8 kB 20.9 MB/s eta 0:00:00
Downloading tokenizers-0.21.4-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 34.3 MB/s eta 0:00:00
Installing collected packages: tokenizers, transformers, sentence-transformers
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.22.2
    Uninstalling tokenizers-0.22.2:
      Successfully uninstalled tokenizers-0.22.2
  Attempting uninstall: transformers
    Found existing installation: transformers 4.57.6
    Uninstalling transformers-4.57.6:
      Successfully uninstalled transformers-4.57.6
  Attempting uninstall: sentence-transformers
    Found existing installation: sentence-transformers 5.7.0
    Uninstalling sentence-transformers-5.7.0:
      Successfully uninstalled sentence-transformers-5.7.0
Successfully installed sentence-transformers-5.4.0 tokenizers-0.21.4 transformers-4.52.0

### Build and validate

The build rechecks the Phase 1 acceptance boundary, loads E5 directly, calls the production `build_release()`, and validates the resulting hashes. The existing `CURRENT` release is reused for unchanged E5 rows when available, but `CURRENT` is not changed here.

In [5]:
print("transformers          :", importlib_metadata.version("transformers"))
print("sentence-transformers :", importlib_metadata.version("sentence-transformers"))

RELEASE_ID              = "aic2026-full-20260817-r01"
ALLOW_RESIDUAL_FAILURES = False
RELEASE_PATH            = RELEASES_ROOT / RELEASE_ID

if (RELEASE_PATH.exists()) :
    print("Release already exists; skipping immutable build:", RELEASE_PATH)
else :
    build_summary = build_corpus_release(
        artifact_root           = FULL_CORPUS_ROOT,
        release_id              = RELEASE_ID,
        allow_residual_failures = ALLOW_RESIDUAL_FAILURES,
    )
    print(json.dumps(build_summary, ensure_ascii = False, indent = 2))

transformers          : 4.52.0
sentence-transformers : 5.4.0
Loading E5 document encoder...

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/128 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_xlm-roberta_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/690 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.12G [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.1M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/964 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/271 [00:00<?, ?B/s]

Batches:   0%|          | 0/1633 [00:00<?, ?it/s]

Release     : aic2026-full-20260817-r01
Videos      : 1,478
Windows     : 26,163 physical / 26,117 searchable
Release path: /content/drive/MyDrive/aic26/asr_model_comparison/production_full_corpus/phase2/releases/aic2026-full-20260817-r01
{
  "created_at_utc": "2026-08-19T08:34:09.544198+00:00",
  "release_id": "aic2026-full-20260817-r01",
  "release_path": "/content/drive/MyDrive/aic26/asr_model_comparison/production_full_corpus/phase2/releases/aic2026-full-20260817-r01",
  "previous_release": null,
  "corpus_identity": "4109e8a68309ae33de9a70add93010008f0897ecf65a58af67f0193a1535ded1",
  "video_count": 1478,
  "physical_window_count": 26163,
  "eligible_window_count": 26117,
  "embedding_shape": [
    26117,
    1024
  ],
  "embedding_dtype": "float32",
  "transcripts_size_bytes": 209010777,
  "bm25_size_bytes": 29458490,
  "e5_size_bytes": 106975360,
  "release_size_bytes": 215341986,
  "phase1_acceptance": {
    "schema_version": "1.0",
    "accepted_at_utc": "2026-08-19T08:13:37.223135+00:00",
    "inventory_identity": "466408aa4d89e7e0412def939a5281081c17dfa1c151f8bf34e4538e7e1b23b4",
    "inventory_verified_at_utc": "2026-08-19T08:02:01.403600+00:00",
    "total_expected_videos": 1478,
    "complete_videos": 1478,
    "physical_window_count": 26163,
    "eligible_window_count": 26117,
    "residual_failed_window_count": 0,
    "residual_failed_window_ids": [],
    "residual_failures_explicitly_accepted": false,
    "blockers": [],
    "passed": true
  },
  "passed": true
}

In [6]:
validation = validate_corpus_release(FULL_CORPUS_ROOT, RELEASE_ID)
print(json.dumps(validation, ensure_ascii = False, indent = 2))

build_summary_path = REPORTS_ROOT / "phase2_build_summary.json"
if (build_summary_path.is_file()) :
    build_summary = read_json(build_summary_path)
    storage_df = pd.DataFrame([
        {"artifact" : "Phase 1 transcripts", "GiB" : build_summary["transcripts_size_bytes"] / 1024**3},
        {"artifact" : "BM25", "GiB" : build_summary["bm25_size_bytes"] / 1024**3},
        {"artifact" : "E5 embeddings", "GiB" : build_summary["e5_size_bytes"] / 1024**3},
        {"artifact" : "Complete release", "GiB" : build_summary["release_size_bytes"] / 1024**3},
    ])
    display(storage_df)

{
  "validated_at_utc": "2026-08-19T08:34:17.290182+00:00",
  "release_id": "aic2026-full-20260817-r01",
  "release_path": "/content/drive/MyDrive/aic26/asr_model_comparison/production_full_corpus/phase2/releases/aic2026-full-20260817-r01",
  "corpus_identity": "4109e8a68309ae33de9a70add93010008f0897ecf65a58af67f0193a1535ded1",
  "video_count": 1478,
  "physical_window_count": 26163,
  "eligible_window_count": 26117,
  "embedding_shape": [
    26117,
    1024
  ],
  "embedding_dtype": "float32",
  "bm25_document_count": 26117,
  "verify_hashes": true,
  "passed": true
}

              artifact       GiB
0  Phase 1 transcripts  0.194656
1                 BM25  0.027435
2        E5 embeddings  0.099629
3     Complete release  0.200553

## 5. Benchmark and activation

Load the normal production retrieval engine and run visible first-stage and reranked searches. The benchmark checks deterministic ordering, score/timing validity, supporting-window ownership, and the production candidate-pair cap.

If you later provide a CSV with `query` and `target_video_id`, the same cell can also calculate first-stage Recall@30/50/75/100. Activation stays disabled until you explicitly change the flag.

In [7]:
BENCHMARK_QUERIES = [
    "Đồng Nai",
    "năm con hổ con",
    "bốn phi hành gia mặc áo đen",
    "tàu vũ trụ nghiên cứu ánh sáng cực quang",
    "một giống hổ quý hiếm ở miền Nam",
]
BENCHMARK_REPETITIONS = 3
BENCHMARK_TOP_K        = 50
GROUND_TRUTH_FILE : Path | None = None

ground_truth = None
if (GROUND_TRUTH_FILE is not None) :
    ground_truth_df = pd.read_csv(GROUND_TRUTH_FILE)
    ground_truth    = ground_truth_df[["query", "target_video_id"]].to_dict("records")

benchmark_summary = benchmark_release(
    artifact_root = FULL_CORPUS_ROOT,
    release_id    = RELEASE_ID,
    queries       = BENCHMARK_QUERIES,
    repetitions   = BENCHMARK_REPETITIONS,
    top_k         = BENCHMARK_TOP_K,
    ground_truth  = ground_truth,
    device        = "cuda",
)

benchmark_df = pd.read_csv(REPORTS_ROOT / "benchmark_query_results.csv")
display(benchmark_df)
print(json.dumps(benchmark_summary["aggregate"], ensure_ascii = False, indent = 2))

if ("candidate_recall" in benchmark_summary) :
    print(json.dumps(benchmark_summary["candidate_recall"], ensure_ascii = False, indent = 2))

config.json:   0%|          | 0.00/795 [00:00<?, ?B/s]

WARNING:sentence_transformers.util.decorators:The Transformer `cache_dir` argument is deprecated. Please pass `cache_dir` via `model_kwargs`, `processor_kwargs`, and/or `config_kwargs` instead.

model.safetensors:   0%|          | 0.00/2.27G [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.1M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/964 [00:00<?, ?B/s]

Benchmark:   0%|          | 0/30 [00:00<?, ?search/s]

,query,mode,repetition,top_video_id,total_ms,bm25_ms,e5_encode_ms,dense_search_ms,first_stage_fusion_ms,video_aggregation_ms,candidate_selection_ms,bge_ms,candidate_fusion_ms,result_build_ms,candidate_pair_count,reranker_batch_size,validation_errors
0,Đồng Nai,first_stage,1,K13_V019,78.892665,1.806436,46.332700,22.515279,0.640865,3.952465,0.000000,0.000000,0.000000,3.421321,0,NaN,[]
1,Đồng Nai,first_stage,2,K13_V019,63.155149,0.566768,33.342070,23.699961,0.569263,1.642919,0.000000,0.000000,0.000000,3.116795,0,NaN,[]
2,Đồng Nai,first_stage,3,K13_V019,73.261733,0.606581,37.342343,28.885040,0.648393,1.959685,0.000000,0.000000,0.000000,3.580728,0,NaN,[]
3,năm con hổ con,first_stage,1,L21_V029,63.660241,0.749592,34.155348,23.234828,0.560217,1.522109,0.000000,0.000000,0.000000,3.216766,0,NaN,[]
4,năm con hổ con,first_stage,2,L21_V029,70.471873,0.620203,38.589247,25.558180,0.601575,1.690408,0.000000,0.000000,0.000000,3.197906,0,NaN,[]
5,năm con hổ con,first_stage,3,L21_V029,61.604134,0.645509,32.461450,22.847819,0.568867,1.566781,0.000000,0.000000,0.000000,3.294869,0,NaN,[]
6,bốn phi hành gia mặc áo đen,first_stage,1,K02_V026,66.848965,0.891852,37.617279,22.840825,0.541600,1.609398,0.000000,0.000000,0.000000,3.137323,0,NaN,[]
7,bốn phi hành gia mặc áo đen,first_stage,2,K02_V026,61.331073,0.891492,32.250698,22.733257,0.580391,1.533330,0.000000,0.000000,0.000000,3.115849,0,NaN,[]
8,bốn phi hành gia mặc áo đen,first_stage,3,K02_V026,66.327802,2.994890,35.330875,22.653514,0.498433,1.560066,0.000000,0.000000,0.000000,3.078950,0,NaN,[]
9,tàu vũ trụ nghiên cứu ánh sáng cực quang,first_stage,1,L21_V015,60.664480,0.716953,32.642704,21.843035,0.513251,1.552061,0.000000,0.000000,0.000000,3.180443,0,NaN,[]
10,tàu vũ trụ nghiên cứu ánh sáng cực quang,first_stage,2,L21_V015,65.307199,0.737735,35.964629,22.961654,0.578241,1.620392,0.000000,0.000000,0.000000,3.213166,0,NaN,[]
11,tàu vũ trụ nghiên cứu ánh sáng cực quang,first_stage,3,L21_V015,64.852919,0.755722,33.559995,24.927906,0.532081,1.614979,0.000000,0.000000,0.000000,3.236094,0,NaN,[]
12,một giống hổ quý hiếm ở miền Nam,first_stage,1,L21_V029,66.857941,3.131771,35.690066,22.492596,0.555665,1.606222,0.000000,0.000000,0.000000,3.168798,0,NaN,[]
13,một giống hổ quý hiếm ở miền Nam,first_stage,2,L21_V029,62.599801,1.292237,32.896900,22.782142,0.572425,1.637296,0.000000,0.000000,0.000000,3.201218,0,NaN,[]
14,một giống hổ quý hiếm ở miền Nam,first_stage,3,L21_V029,78.492241,1.488789,36.306012,27.057323,0.658223,5.873432,0.000000,0.000000,0.000000,6.889976,0,NaN,[]
15,Đồng Nai,reranked,1,K16_V012,1534.624108,0.416351,33.391399,23.204771,0.559831,1.575437,2.018515,1465.505633,0.280729,3.736771,150,32.0,[]
16,Đồng Nai,reranked,2,K16_V012,1532.506577,2.457900,34.273530,30.066496,0.859813,3.871432,4.326729,1448.201719,0.252862,4.059126,150,32.0,[]
17,Đồng Nai,reranked,3,K16_V012,1546.534530,0.481090,31.813737,33.671398,2.126447,2.888645,4.342326,1462.719595,0.266024,3.472232,150,32.0,[]
18,năm con hổ con,reranked,1,L21_V029,1564.636441,0.985649,36.674104,27.889937,0.633773,3.735256,4.094567,1486.057544,0.208972,2.190565,150,32.0,[]
19,năm con hổ con,reranked,2,L21_V029,1538.421638,2.426496,24.821524,21.737403,0.521972,1.614847,2.007485,1467.226669,2.361652,7.997514,150,32.0,[]
20,năm con hổ con,reranked,3,L21_V029,1680.966178,5.514288,63.476463,40.254525,0.557423,7.386473,4.532310,1538.416406,2.372833,8.074311,150,32.0,[]
21,bốn phi hành gia mặc áo đen,reranked,1,K02_V026,1763.219456,2.637658,65.408235,50.483374,0.696059,5.756676,6.330851,1612.365179,0.282907,8.001083,150,32.0,[]
22,bốn phi hành gia mặc áo đen,reranked,2,K02_V026,1700.803754,4.274498,49.147590,39.042136,0.553329,3.734566,7.753958,1588.316153,0.290663,3.725097,150,32.0,[]
23,bốn phi hành gia mặc áo đen,reranked,3,K02_V026,1633.354593,1.036956,39.448893,29.230383,0.633189,1.729130,2.044805,1554.676649,0.201637,2.084960,150,32.0,[]
24,tàu vũ trụ nghiên cứu ánh sáng cực quang,reranked,1,L21_V015,1532.197337,1.183488,27.430073,21.716249,0.542862,1.621477,2.036573,1473.048641,0.203775,2.179159,150,32.0,[]
25,tàu vũ trụ nghiên cứu ánh sáng cực quang,reranked,2,L21_V015,1538.938678,3.367360,24.001967,21.898600,0.560210,1.693514,1.971998,1481.083736,0.215823,2.032374,150,32.0,[]
26,tàu vũ trụ nghiên cứu ánh sáng cực quang,reranked,3,L21_V015,1548.595128,1.181439,26.669493,21.907697,0.602116,1.622868,2.008027,1486.584818,0.292069,3.809599,150,32.0,[]
27,một giống hổ quý hiếm ở miền Nam,reranked,1,L21_V029,1606.098519,2.650695,37.125603,33.593555,1.690210,3.217693,6.734068,1513.116032,0.252590,3.613586,150,32.0,[]
28,một giống hổ quý hiếm ở miền Nam,reranked,2,L21_V029,1568.006079,2.556316,35.080272,27.998855,0.587285,1.737254,2.013781,1489.323232,0.278080,3.520922,150,32.0,[]
29,một giống hổ quý hiếm ở miền Nam,reranked,3,L21_V029,1611.606620,3.471086,32.443687,28.485613,0.519494,3.885898,2.051729,1524.838789,0.273350,7.739184,150,32.0,[]

{
  "first_stage": {
    "total_ms": {
      "mean": 66.9552144,
      "p50": 65.307199,
      "p95": 78.6123682,
      "max": 78.892665
    },
    "bm25_ms": {
      "mean": 1.193102,
      "p50": 0.755722,
      "p95": 3.0359542999999998,
      "max": 3.131771
    },
    "e5_encode_ms": {
      "mean": 35.6321544,
      "p50": 35.330875,
      "p95": 40.912282899999994,
      "max": 46.3327
    },
    "dense_search_ms": {
      "mean": 23.802223933333334,
      "p50": 22.847819,
      "p95": 27.605638099999997,
      "max": 28.88504
    },
    "first_stage_fusion_ms": {
      "mean": 0.5746326666666667,
      "p50": 0.569263,
      "p95": 0.651342,
      "max": 0.658223
    },
    "video_aggregation_ms": {
      "mean": 2.0627695333333333,
      "p50": 1.614979,
      "p95": 4.528755099999998,
      "max": 5.873432
    },
    "candidate_selection_ms": {
      "mean": 0.0,
      "p50": 0.0,
      "p95": 0.0,
      "max": 0.0
    },
    "bge_ms": {
      "mean": 0.0,
      "p50": 0.0,
      "p95": 0.0,
      "max": 0.0
    },
    "candidate_fusion_ms": {
      "mean": 0.0,
      "p50": 0.0,
      "p95": 0.0,
      "max": 0.0
    },
    "result_build_ms": {
      "mean": 3.4700134666666664,
      "p50": 3.201218,
      "p95": 4.573502399999996,
      "max": 6.889976
    },
    "candidate_pair_count": {
      "mean": 0.0,
      "p50": 0.0,
      "p95": 0.0,
      "max": 0.0
    }
  },
  "reranked": {
    "total_ms": {
      "mean": 1593.3673090666664,
      "p50": 1564.636441,
      "p95": 1719.5284646,
      "max": 1763.219456
    },
    "bm25_ms": {
      "mean": 2.3094180000000004,
      "p50": 2.4579,
      "p95": 4.6464349999999985,
      "max": 5.514288
    },
    "e5_encode_ms": {
      "mean": 37.41377133333333,
      "p50": 34.27353,
      "p95": 64.0559946,
      "max": 65.408235
    },
    "dense_search_ms": {
      "mean": 30.0787328,
      "p50": 28.485613,
      "p95": 43.32317969999999,
      "max": 50.483374
    },
    "first_stage_fusion_ms": {
      "mean": 0.7762675333333333,
      "p50": 0.587285,
      "p95": 1.8210810999999996,
      "max": 2.126447
    },
    "video_aggregation_ms": {
      "mean": 3.071411066666666,
      "p50": 2.888645,
      "p95": 6.2456150999999975,
      "max": 7.386473
    },
    "candidate_selection_ms": {
      "mean": 3.6178481333333328,
      "p50": 2.051729,
      "p95": 7.040034999999999,
      "max": 7.753958
    },
    "bge_ms": {
      "mean": 1506.0987196667156,
      "p50": 1486.5848180002104,
      "p95": 1595.530860800136,
      "max": 1612.365179000335
    },
    "candidate_fusion_ms": {
      "mean": 0.5355977333333333,
      "p50": 0.27335,
      "p95": 2.3650062999999997,
      "max": 2.372833
    },
    "result_build_ms": {
      "mean": 4.4157655333333325,
      "p50": 3.725097,
      "p95": 8.0230514,
      "max": 8.074311
    },
    "candidate_pair_count": {
      "mean": 150.0,
      "p50": 150.0,
      "p95": 150.0,
      "max": 150.0
    }
  }
}

In [8]:
ACTIVATE_RELEASE = False

if (ACTIVATE_RELEASE) :
    final_summary = activate_corpus_release(FULL_CORPUS_ROOT, RELEASE_ID)
    print(json.dumps(final_summary, ensure_ascii = False, indent = 2))
else :
    print("Activation is disabled. Review the release validation and benchmark results first.")

Activation is disabled. Review the release validation and benchmark results first.